### ISSUE TITLE
JsonPointer: ability to set/create a value in a document

### ISSUE THREAD

**Issue by queil** [gregsdennis/json-everything#170]
This proposal covers two use cases:

* If a pointer evaluates to true in a given document I'd like to be able to set the value of that node to a new value (either given as `JsonElement` or a JSON string.

* If a pointer evaluates to false I'd still like to set the value of that node but I'd like the missing intermediary nodes to get automatically created.

**Alternatives**

This functionality exists in [rapidjson](http://rapidjson.org/md_doc_pointer.html). I could not find anything similar in the .NET ecosystem.

**Comment by gregsdennis** [comment]
The primary issue that comes from this is pointers that contain numeric segments.  Are they array indices, or string keys in an object?  What happens if the pointer is `/foo/3/bar`?  How is the `3` interpreted?  What happens if `/foo` isn't an array, or if it _is_ an array but only has one item?

This has been explored in the JSON Patch specification (which is really the tool I think you need), specifically around the [`add` operation](https://datatracker.ietf.org/doc/html/rfc6902#section-4.1).

I do think, however, that successive JSON Patch operations will give you what you're looking for.

Note: I had to do some pretty janky things to get JSON Patch to work.  It looks like System.Text.Json is getting an editable DOM in .Net 6, which will make a lot of this easier and hopefully faster.

**Comment by queil** [comment]
Ok, I see - JsonPointer just doesn't bear enough information to make it work in an unambiguous way. Rapidjson must have quite an opinionated/limited implementation. It's shame that there is no standard for Json Path yet as it would probably make something like this possible.

I am aware of the Json Patch approach but hoped for something less cumbersome.

> I had to do some pretty janky things to get JSON Patch to work
Yeah, I guess lots of parsing to create JSON Elements without an editable DOM?

Thanks for the explanation - I am closing the issue.

**Comment by queil** [comment]
> it's not going to help you edit the JSON

Yes, I am aware of that. It still would be hacky.

> it looks like Patch is the only thing that'll do that in a formalized way

Yeah, as you mentioned earlier a successive application of patches would work. However, I'll just stick with manually adding the necessary JSON this time rather than using patches.
