### ISSUE TITLE
Unique Keys Validation not Working?

### ISSUE THREAD

**Issue by sacvalleytech** [gregsdennis/json-everything#181]
**Environment**
- Nuget Package:  JsonSchema.Net.UniqueKeys 1.0.0
- OS: Windows 11
- .Net Target: net5.0

**How can I help you today?**
The JSON schema validation for unique keys does not seem to work (or I am missing something)

Following example: https://gregsdennis.github.io/json-everything/usage/vocabs-unique-keys.html

**Additional context**

**Schema**

```json
{
  "$schema": "https://gregsdennis.github.io/json-everything/meta/unique-path",
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "foo": { "type": "integer" }
    }
  },
  "uniqueKeys": [
    "/foo"
  ]
}
```
**Input**

```json

[
  { "foo": 8 },
  { "foo": 12 },
  { "foo": 42 }
]

```

**Example**

```c#
  var s = JsonSchema.FromFile("schema.json");
  var d = System.Text.Json.JsonDocument.Parse(File.ReadAllText("input.json"));
  var r = s.Validate(d.RootElement);

  Console.WriteLine(JsonSerializer.Serialize(r));
```

**Output**

`{"valid":false,"keywordLocation":"#","instanceLocation":"#"}`

**Comment by gregsdennis** [comment]
Looks like my example is wrong. The ducks day that the correct URI for the vocab is `https://gregsdennis.github.io/json-everything/vocabs-unique-keys`.  Update `$schema` to that, and it should work.

**Comment by sacvalleytech** [comment]
Still no dice... I had a look at the Unit Tests in the project and found this line in the test setup
 `Json.Schema.UniqueKeys.Vocabularies.Register();`

If I add that to my code I get the following error during Schema Load

`
Could not load type 'Json.Pointer.JsonPointer' from assembly 'JsonSchema.Net.UniqueKeys, Version=1.0.0.0
`

**Comment by gregsdennis** [comment]
What versions of JsonSchema.Net and JsonPointer.Net are you using?

**Comment by sacvalleytech** [comment]
`
JsonSchema.Net - 1.11.5
JsonSchema.Net.UniqueKeys - 1.0.0

**Comment by gregsdennis** [comment]
I may need to release a new version of unwire keys to reference 2.0 on pointers.  I can do that tonight.

**Comment by sacvalleytech** [comment]
Ok great thanks!

I tried downgrading to 1.11.4 which references `JsonPointer.Net 1.4.0` 

Now I get a different error: `System.Text.Json.JsonException: 'Expected object'`

So I am not sure if that will fix it or something else is going on.

**Comment by gregsdennis** [comment]
@sacvalleytech your example works fine on https://json-everything.net/json-schema, which is using the latest of all of the packages.

**Comment by sacvalleytech** [comment]
Interesting... its fails/succeeds based on the order of the line `Json.Schema.UniqueKeys.Vocabularies.Register();`

**Works**

```c#
var schema = JsonSchema.FromText(schemaText);
var instance = JsonDocument.Parse(instanceText).RootElement;

Json.Schema.UniqueKeys.Vocabularies.Register();
ValidationOptions.Default.OutputFormat = OutputFormat.Verbose;
```


**Fails**
```c#
Json.Schema.UniqueKeys.Vocabularies.Register();
ValidationOptions.Default.OutputFormat = OutputFormat.Verbose;

var schema = JsonSchema.FromText(schemaText);
var instance = JsonDocument.Parse(instanceText).RootElement;
```

**Comment by gregsdennis** [comment]
Well that is a peculiar result.  Good find. I'll play with it and release a fix when I can.

Are you unblocked for now?

**Comment by sacvalleytech** [comment]
Yes I can work around that... thanks for the help!

**Comment by sacvalleytech** [comment]
I tried cloning the repo and created the same test console app... but referenced the projects directly (instead of NuGet). The error is gone now... so it does seem to be some sort of dependency issue with the NuGet packages.

**Comment by gregsdennis** [comment]
I did an update of the nuget package and imported from a local nuget repo (just a folder on my disk).  That seemed to fix the problem.  I'm releasing new versions of all of the dependent packges (which is basically all of them).

A long time ago, I had done some work playing around with the different versions and how they interoperate with nuget packaging.  I wrote a [blog post](https://gregsdennis.github.io/coding-for-smarties/2016/01/21/how-to-version-assemblies-destined-for-nuget.html) about it.  To my surprise, this became the general approach for most people after Jon Skeet found it and referenced it in a blog post of his own when he was updating NodaTime to v2.  (In fact, MS now highlights this approach in their docs, but they don't reference my post.)

According to that approach, I should have released new major versions of everything.

A few months ago, I discovered that starting with .Net Core 3.1, it seemed that the framework didn't care anymore about the version attributes in the assembly file because I was able to reference new major versions without having to rebuild dependent assemblies.  As a result, when I updated JsonPointer.Net, I figured I'd be fine by just releasing a patch version update of the direct dependencies.

It seems that there's still an issue with downstream dependencies, though.  I guess I should just stick with the approach I laid out before.
