### ISSUE TITLE
Example on stream and validation

### ISSUE THREAD

**Issue by Spirch** [gregsdennis/json-everything#186]
This should be easy to answer, I have looked around and I can't find a way to validate a json file without loading it in memory.

I think I read somewhere that it was possible to validate from stream.

Is it possible to have an example?

(searching online always return result not about json-everything / jsonschema.net)

**Comment by gregsdennis** [comment]
Sorry for not getting back to you sooner.

Unfortunately, there is no way to validate directly from the stream, at least not with the architecture I have.

My flow is heavily oriented around the schema rather than the instance.  Validation proceeds through the schema's keywords and randomly accesses the instance in order to determine if it's compliant.

In order to validate from a stream, I'd have to turn all of that around and completely validate each instance value as it came through.  Having a schema where a property can have requirements at several locations makes this difficult.

```json
{
  "oneOf": [
    { "properties": { "foo": { "type": "integer", "maximum": 10 } } },
    { "properties": { "foo": { "type": "integer", "minimum": 20 } } },
  ]
}
```

Every time I read a property, I'd have to scan the entire schema to find where it might be validated.
