### ISSUE TITLE
JsonSchema doesn't recognize (or list) non supported drafts

### ISSUE THREAD

**Issue by bard83** [gregsdennis/json-everything#19]
**Describe the bug**
Schema with draft 07 doesn't recognized the Schema draft 04.

Probably should be considered as new feature. In our validators we want to enforce the use the draft 07 and we don't want to support other drafts at the moment. Some additional information should be provided from thte JsonSchema object. 

**Expected behavior**
Schema draft 04 should be recognized from Schema draft 07. 

**To Reproduce**
```
using Manatee.Json;
using Manatee.Json.Schema;
using System;
using System.Text.Json;

using JsonEverythingSchema = Json.Schema.JsonSchema;
using ManateeJsonSchema = Manatee.Json.Schema.JsonSchema;
using ManateeJsonSerializer = Manatee.Json.Serialization.JsonSerializer;


namespace jsonschema
{
    class Program
    {
        private static readonly ManateeJsonSerializer _serializer = new ManateeJsonSerializer();

        static void Main(string[] args)
        {
            var json = "{}";
            Console.WriteLine($"Validate {json} against {MyInvalidSchema}");
            ManateeValidation(MyInvalidSchema, json); // Expected Schema Invalid
            JsonEverythingValidation(MyInvalidSchema, json); // Expected Schema Invalid
        }

        private static void JsonEverythingValidation(string schema, string json)
        {
            var jsSchema = JsonDocument.Parse(schema).RootElement;
            var schemaValidationResult = Json.Schema.MetaSchemas.Draft7.Validate(jsSchema);
            if (!schemaValidationResult.IsValid)
            {
                Console.Error.WriteLine($"JsonEverything: Schema is invalid - reason {schemaValidationResult.Message}");
                return;
            }

            var jsonSchema = JsonEverythingSchema.FromText(schema);

            var validationResult = jsonSchema.Validate(JsonDocument.Parse(json).RootElement);

            Console.WriteLine($"JsonEverything: Valid {validationResult.IsValid} - {validationResult.Message}");
        }

        private static void ManateeValidation(string schema, string json)
        {

            var jsonSchema = _serializer.Deserialize<ManateeJsonSchema>(JsonValue.Parse(schema));
            var schemaResult = jsonSchema.ValidateSchema();
             if (!schemaResult.IsValid)
            {
                Console.Error.WriteLine("Manatee: Schema is invalid");
                return;
            }

            if ((schemaResult.SupportedVersions & JsonSchemaVersion.Draft07) == 0)
            {
                Console.Error.WriteLine("Manatee: Schema is invalid expected draft 07");
                return;
            }

            var validationResult = jsonSchema.Validate(JsonValue.Parse(json));

            Console.WriteLine($"Manatee: Valid {validationResult.IsValid} - {validationResult.AdditionalInfo.ToString()}");
        }

        private static readonly string MyInvalidSchema = "{\n  \"$schema\": \"http://json-schema.org/draft-04/schema#\"\n}\n";
    }

}

```

**Comment by bard83** [comment]
```
Validate {} against {
  "$schema": "http://json-schema.org/draft-04/schema#"
}

Manatee: Schema is invalid expected draft 07
JsonEverything: Valid True -
```

**Comment by gregsdennis** [comment]
To validate the schema against the meta-schema (the `$schema` keyword), you need to enable meta-schema validation in the options.

```c#
var result = schema.Validate(instance, new SchemaValidationOptions { ValidateMetaSchema = true });
```

**Comment by bard83** [comment]
Ok, I see. 
But this means that the schema is validated against the meta-schema only when a json instance is validated against the schema, doesn't it?

In our use case we validate the schema before, if the schema is valid we cache it otherwise we discard it. When a new json instance needs to be validated against its schema, we pick up the schema from the cache and validate the json instance against it. We want to prevent to cache invalid schema.

**Comment by gregsdennis** [comment]
Maybe we need a third setting for "validate that the meta-schema indicated by `$schema` is known."

Also, this raises a question of whether a schema that specifies a draft 4 meta-schema is a valid draft 7 schema.  I'll need to raise this with the JSON Schema group.

**Comment by gregsdennis** [comment]
Hang on... You're using custom code to validate that it's draft 7 for the Manatee.Json version:

```c#
if ((schemaResult.SupportedVersions & JsonSchemaVersion.Draft07) == 0)
{
    Console.Error.WriteLine("Manatee: Schema is invalid expected draft 07");
    return;
}
```

Do the following:

Check the `$schema` keyword.  If the keyword exists and doesn't match draft 7, don't cache it; otherwise perform the meta-schema validation, and cache accordingly.

Then when validating set the `ValidateAs` option to `Draft.Draft7`, and all of the validation will be processed as such.

---

`json-everything` works differently than Manatee.Json.  It doesn't perform the same kind of keyword analysis (and I don't plan on adding it).

The declared schema serves three functions:

- Validation by the meta-schema: this is enabled by the `ValidateMetaSchema` option.  Having this off (default) essentially skips any validation by the `$schema` keyword.
- Filtering keywords: only the keywords annotated as supporting the draft specified by either the `$schema` keyword (primary) or the `ValidateAs` option (secondary) will be validated.  The fallback to `ValidateAs` happens when the `$schema` keyword doesn't exist or the meta-schema chain back to one of the drafts can't be found (e.g. a custom meta-schema references another custom meta-schema that references draft 6).
- Determining `$ref` behavior.  In draft 2019-09, sibling keywords of `$ref` are processed; prior to draft 2019-09, siblings of `$ref` are ignored.

So in your case, you have a schema that declares draft 4 and this configuration:

- `ValidateMetaSchema` is false (because you pre-validate the schemas against draft 7, which is wrong)
- `ValidateAs` is `Unspecified` (because you're not setting it)

Upon validation, the schema

1. Looks for the `$schema` keyword to determine how to filter the keywords
2. Finds the draft 4 meta-schema `$id`
3. Attempts to find it in the registry
3. Fails to find it
4. Fall back to `ValidateAs` which is `Unspecified`, which means schemas that don't declare a draft will be processed as latest, which currently is draft 2019-09.
5. Validates all keywords that support draft 2019-09.
   -  `$schema` keyword just skips all validation and returns "valid" because `ValidateMetaSchema` is false.

What you're wanting is for the pre-validation of the schema by the draft 7 meta-schema to return "invalid," but that's just not the case.  A schema that declares draft 4 _is a valid draft 7 schema_ (unless it contains specific keywords that changed, like `exclusiveMaximum` which changed from a boolean in draft 4 to a number in draft 6).  Draft 7 doesn't specify that the value of `$schema` MUST be the draft 7 meta-schema `$id` (or lead to a schema that declares it); it just says the value must be an absolute URI.  Since the draft 4 meta-schema `$id` is a valid absolute URI, the validation passes.

**Comment by gregsdennis** [comment]
Accidentally closed when I merged the PR I thought I'd use to address this.  Feel free to reopen if needed.

**Comment by amosonn** [comment]
It seems to me that the keywords are not actually filtered according to the current "active" draft. The code in `ValidationOptions` for `FilterKeywords` only takes care of the siblings of Ref, and does not check the attributes of the keywords to determine if they are valid for the chose draft.

```cs
using Json.Schema;
using System;
using System.Text.Json;

namespace test
{
    class Program
    {
        static void Main(string[] args)
        {
            var schema = JsonSerializer.Deserialize<JsonSchema>(@"
{
    ""dependencies"": {
        ""abc"": [ ""d7"" ]
    },
    ""dependentRequired"": {
        ""abc"": [ ""d9"" ]
    }
}");
            var elems = new[]
            {
                JsonDocument.Parse(@"{}").RootElement,
                JsonDocument.Parse(@"{""abc"": 1}").RootElement,
                JsonDocument.Parse(@"{""abc"": 1, ""d7"": 7}").RootElement,
                JsonDocument.Parse(@"{""abc"": 1, ""d9"": 9}").RootElement,
                JsonDocument.Parse(@"{""abc"": 1, ""d7"": 7, ""d9"": 9}").RootElement,
            };
            var drafts = new[] { Draft.Draft7, Draft.Draft201909 };

            foreach (var d in drafts)
            {
                var opts = new ValidationOptions { ValidateAs = d };
                System.Console.WriteLine("On draft {0}:", d);
                foreach (var e in elems)
                {
                    var val = schema.Validate(e, opts);
                    System.Console.WriteLine("Elem {0} got validation {1}", e, val.IsValid);
                }
            }
        }
    }
}
```

**Comment by bard83** [comment]
@gregsdennis please re-open it.

**Comment by gregsdennis** [comment]
Good catch. Will post an update.

**Comment by gregsdennis** [comment]
v1.6.0 (due out soon) modifies the behavior of this option slightly.  As of this version, it will _require_ that the meta-schema be known or the validation will fail.  This will only affect clients who use schemas that declare custom meta-schemas.  These clients will now need to either manually load the meta-schema or set `ValidationOptions.Fetch` to have it loaded automatically.
