### ISSUE TITLE
Could not resolve reference  error

### ISSUE THREAD

**Issue by joyse1** [gregsdennis/json-everything#212]
**Environment**
- Nuget Package: JsonSchema.Net
- Nuget Version: 2.0.1
- OS:  Win10
- .Net Target: .Net Framework 4.7.2

**Description**
I am getting validation errors when validating json data against json schema:
- Could not resolve reference `#guid` Location: #/ContentDefinitionId
- All values fail against the false schema Location: #/ContentDefinitionId

**To reproduce:**
_Json Schema:_

```json
{
	"$schema": "http://json-schema.org/draft-07/schema#",
	"$id": "http://messagebroker.fff.pl/rpn/dci/kkt.json",
	"type": "object",
	"title": "JSON Schema ",
	"definitions": {
		"#guid": {
			"id": "#guid",
			"title": "Definicja obligatoryjnego GUID (regex)",
			"type": "string",
			"examples": [
				"09C9A8DA-B40F-4E3A-9746-7B10AFEC2C4F",
				"2d9bbb00-878f-49b0-9d48-767ce3e12dee"
			],
			"minLength": 36,
			"maxLength": 36,
			"pattern": "^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12})$"
		}
	},
	"required": [
		"ContentDefinitionId"
	],
	"properties": {
		"ContentDefinitionId": {
			"$ref": "#guid",
			"title": "Identyfikator definicji "
		}
	},
	"additionalProperties": false
}
```

_Json Data:_

```json
{
  "ContentDefinitionId": "fa81bc1d-3efe-4192-9e03-31e9898fef90"
}
```

_Execution Code:_

```c#
var jsonSchema = JsonEverythingSchema.FromFile(schemaPath);
var res = jsonSchema.Validate(jsonDoc.RootElement, new ValidationOptions { OutputFormat = OutputFormat.Detailed, ValidateAs = Draft.Draft7, ValidateMetaSchema = true });
```

**Expected behaviour:**
 Validation passes with newtonsoft.json

**Comment by gregsdennis** [comment]
Thanks for reporting this.  I'll set up a test and see what I can find.

**Comment by gregsdennis** [comment]
It looks like there's an issue either with your schema as you've typed it or with deserialization.  I've uploaded branch `issue212-could-not-resolve-ref` with two tests:

- loading the schema from a file (copied directly from your text above).   This replicates the issue.
- creating the schema inline.  This passes validation, as you expect.

**Comment by gregsdennis** [comment]
Found the issue.  The `"id": "#guid"` should be `"$id": "#guid"`.  If you update this, it will work as expected.  The inline version does this automatically.

Newtonsoft probably (and incorrectly) validates this because it supports draft 4, which was before `id` was changed to `$id` (in draft 6), so it recognizes that as a valid keyword.  However, you've explicitly (via `$schema`) said that this is draft 7, so it shouldn't see `id` as a keyword.   This library properly ignores it.

Interestingly, Visual Studio gets this right as well:

![image](https://user-images.githubusercontent.com/2676804/153140413-acf1be80-257b-4640-9ebe-0463aceaea21.png)

I'm going to go ahead and keep these tests in the suite.

**Comment by joyse1** [comment]
Thank you Greg for investigating my problem. 
I did what you pointed out but in this moment I have another issue - when json schema becomes more complex.
It seems to be something else, so I will report another issue "All values fail against the false schema  issue"
