### ISSUE TITLE
Could we introduce extension methods for validating `JsonDocument`/json string by json schema

### ISSUE THREAD

**Issue by WeihanLi** [gregsdennis/json-everything#237]
**Environment**
- Nuget Package: JsonSchema.Net
- Nuget Version: 2.1.2
- OS: Windows/Linux
- .Net Target: .NET 6

**Can this library make doing something simpler?**

Maybe we could introduce some extensions to make it more easier, for example:

``` c#
public static ValidationResults Validate(this JsonSchema jsonSchema, JsonDocument jsonDocument, ValidationOptions validationOptions = null)
{
    return jsonSchema.Validate(jsonDocument.RootElement, validationOptions);
}

public static ValidationResults Validate(this JsonSchema jsonSchema, string jsonString, ValidationOptions validationOptions = null)
{
    using var jsonDocument = JsonDocument.Parse(jsonString);
    return jsonSchema.Validate(jsonDocument, validationOptions);
}
```

**Describe alternatives you've considered**

Not sure if it's reasonable and valuable to add the `JsonDocument` method as an instance method

**Additional context**

I'm new here, maybe there're some magic ways that I don't know

**Comment by gregsdennis** [comment]
I remember I had some problems with the string one in Manatee.Json.  But because that was due to the JSON model having an implicit cast from string (to make a JSON string), there was ambiguity.  I don't think that'll be an issue for this library.

I think these can be added in. Can you create a PR?

**Comment by WeihanLi** [comment]
Sure, thanks

**Comment by gregsdennis** [comment]
@WeihanLi just letting you know that the move to `JsonNode` is causing a need to remove the extension that takes a string.  It turns out that the implicit `string` -> `JsonNode` cast is taking precedence on these calls, which means the extension method isn't used.

This is a breaking change that will only appear at runtime.  Your existing code that uses this extension method will likely still compile, but validations will now fail.

**Comment by WeihanLi** [comment]
@gregsdennis many thanks
