### ISSUE TITLE
Feature request: (Re)Add support for UriTemplates in Json Scemas.

### ISSUE THREAD

**Issue by m-abs** [gregsdennis/json-everything#244]
**Environment**
- Nuget Package: sonSchema.Net
- Nuget Version: 2.2.0
- OS: Linux
- .Net Target: Core 6.x

**Describe the functionality that isn't covered by this suite**
Support for UriTemplates using an external library, like `Resta.UriTemplates`.

Should be fairly easy modify https://github.com/gregsdennis/json-everything/blob/master/JsonSchema/Formats.cs#L178
```c#
	private static bool CheckUriTemplate(JsonElement element)
	{
		if (element.ValueKind != JsonValueKind.String) return true;

                try
                {
                    new Resta.UriTemplates.UriTemplate(element.GetString));
                    return true;
                } catch {
                    return false;
                }
	}
```

**Additional context**
We need to validate JSON feeds (OPDS 2.0) containing Uri Templates, currently `JsonScema` throws an exception on validation because DotNet Core doesn't include `UriTemplate` from WCF.

**Comment by gregsdennis** [comment]
I understand the desire to have this added, but I prefer to have the support come from .Net rather than introduce a dependency, especially when most people probably won't need it.

There are also [this issue](https://github.com/dotnet/runtime/issues/23848), which has been open for quite a while, and [this package](https://www.nuget.org/packages/UriTemplate.Core/), which is a direct port of the WCF class.

Until .Net (finally) decides to reintroduce this class, I prefer to leave it unsupported so that consumers (like you) can add it if they need it.

You can add formats easily using the `Formats.Register()` static method.  Just create a new `PredicateFormat` instance using the `CheckUriTemplate()` method you have above, and register it.  The registration will overwrite anything I already have in place.  Doing this automatically makes your new format implementation available during deserialization as well.

**Comment by m-abs** [comment]
Thank you for the very quick response, I ended up with this class.

```c#
using System.Text.Json;
using Json.Schema;
using Resta.UriTemplates;

class UriTemplateFormat : Format
{
  public UriTemplateFormat() : base("uri-template")
  {
  }

  public override bool Validate(JsonElement element)
  {
    return Validate(element, out var _);
  }

  public override bool Validate(JsonElement element, out string? errorMessage)
  {
    errorMessage = null;
    if (element.ValueKind != JsonValueKind.String) { return true; }

    try
    {
      new UriTemplate(element.GetString());
      return true;
    }
    catch (Exception e)
    {
      errorMessage = e.Message;
      return false;
    }
  }
}
```

**Comment by gregsdennis** [comment]
Thanks for posting your solution back. I'll update the docs to link here as an example for future users with similar questions.
