### ISSUE TITLE
RegExFormat in the Json.Schema validates all strings as valid

### ISSUE THREAD

**Issue by YaroslavHuriev** [gregsdennis/json-everything#246]
**Describe the bug**
I noticed that `RegExFormat` validates all the strings regardless if they're valid or not. It seems like the problem is that `ValueKind` element check returns `false`, although it should return `true`.

https://github.com/gregsdennis/json-everything/blob/25b9feb2483596b770ef9857a8de5b400fad619d/JsonSchema/RegexFormat.cs#L32

**Comment by gregsdennis** [comment]
`RegexFormat` is a `Format` implementation that uses a RegEx to perform validations.  These formats are only applicable to strings, so if the value is not a string, it must pass.

You can see how this class is used by looking in the `Formats` class.

I'll have a look at the tests around RegEx-powered formats later today to verify they're working.  Since these tests are optional, they don't fail; they assert as "Inconclusive."

**Comment by gregsdennis** [comment]
Turns out I also neglected to implement the `Validate()` that also returns an error message. 🤦   I'll have an update out soon.

**Comment by gregsdennis** [comment]
@YaroslavHuriev I'm pushing out an update soon.  Please also be aware that you must set `RequireFormatValidation` to `true` in the options when you call `.Validate()`.  Without this, all formats will (in most cases) pass because they won't be checked.  Instead, you'll just get an annotation.
