### ISSUE TITLE
Schema.FromFile not resolving subschema

### ISSUE THREAD

**Issue by danny-bos-tata** [gregsdennis/json-everything#255]
**Environment**
- Nuget Package: JsonSchema.Net
- Nuget Version: 2.3.0
- OS: Windows 10
- .Net Target: .NET 6.0

I have two schema's, one referring to another:

**parent.json**
```json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "parent.json",
  
  "$comment": "Tralala",
  "type": "object",

  "properties": {

    "header": {
      "$ref": "child.json#/$defs/header"
    }
  }
}
```
**child.json**
```json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "child.json",
  "$defs": {
    "header": {
      "type": "object",
      "additionalProperties": false,

      "properties": {
        "to": { "type": [ "string" ] }
      }
    }
  }
}
```
**json data to validate**
```json
{
  "header": {
    "to": "abc"
  }
}
```

Both files are copied to the output directory.
I'm trying to validate json using JsonSchema.FromFile:

```c#
public ValidationResults ValidateByFile(ref Utf8JsonReader utf8JsonReader, string schemaJsonFile)
{
    JsonElement jsonElement = JsonElement.ParseValue(ref utf8JsonReader)!;

    var schema = JsonSchema.FromFile(schemaJsonFile);

    return schema.Validate(jsonElement, new ValidationOptions
    {
        OutputFormat = OutputFormat.Detailed,
    });
}
```
I call this function from a test using MsTest:
```c#
var result = new SchemaValidator().ValidateByFile(ref reader, @"./JsonFiles/parent.json");
result.IsValid.Should().BeTrue();
```
I get this error message:
```
"Could not resolve base URI \"file:///C:/Projecten/IJM.Library/src/Json/Json.UnitTests/bin/Debug/net6.0/JsonFiles/child.json\""
```
When I try to load the file with my browser (chrome), the file content is loaded, so it's is actually in that location.

I can work around this problem by setting up how the SchemaRegistry needs to fetch the child like this:

```c#
public ValidationResults ValidateByFile(ref Utf8JsonReader utf8JsonReader, string schemaJsonFile)
{
    JsonElement jsonElement = JsonElement.ParseValue(ref utf8JsonReader)!; // what is !   ????

    var schema = JsonSchema.FromFile(schemaJsonFile);

    return schema.Validate(jsonElement, new ValidationOptions
    {
        OutputFormat = OutputFormat.Detailed,
        SchemaRegistry = {
            Fetch = uri => {
                return JsonSchema.FromFile(uri.AbsolutePath);
            }
        }
    });
}
```

I don't understand why the child.json is not loaded, they are both in the same directory.

**Comment by gregsdennis** [comment]
You workaround is one of two correct solutions.

As specified by JSON Schema, JsonSchema.Net's default behavior is that it will not attempt to download or otherwise retrieve your files.  This means that you'll need to do one of two things:

1. Tell it how to download new schemas based on a URI (which is what your workaround does).
2. Preload and register all of your schemas.

JSON Schema doesn't have a hard preference, but it leans more toward the latter option.  You can see that the test suite runner is doing the same thing its [setup](https://github.com/gregsdennis/json-everything/blob/f643f24964080ba4f9d733254e45a656dfe82b24/JsonSchema.Tests/Suite/Suite.cs#L90-L92).  It knows where all of the potentially referenced schemas are (they're all in a single folder), and it registers them.  Once the schemas are registered, they can be resolved.

More information about how JsonSchema.Net can be found in the [documentation](https://json-everything.net/json-schema) under "Managing references"

**Comment by danny-bos-tata** [comment]
Thank you for your fast response Dennis. In the last our I indeed spend some time preloading the schema's. I will look into that setup.
