### ISSUE TITLE
JsonPath to JsonPointer

### ISSUE THREAD

**Issue by SGStino** [gregsdennis/json-everything#287]
**Environment**
- Nuget Package:  JsonPath.Net
- Nuget Version: 0.2.0+
- OS: Any
- .Net Target: Any

**Can this library make doing something simpler?**
Convert from a PathMatch to JsonPointer, or from a JsonPath to a JsonPointer to extract the path of a match.

**Describe alternatives you've considered**
I'm freezing my package version at 0.1.x until i found a way around this.

**Additional context**
Since the change in PathMatch.Location from JsonPointer to JsonPath I lost the ability to quickly parse the matched path. 

Consider the following RoslynPad snippet:
```csharp
#r "nuget:JsonPath.Net/0.1.14"
using System.Text.Json;
using Json.Path;
using Json.Pointer;

var item = JsonSerializer.SerializeToElement(new
{
    hello = new
    {
        value = 15
    }
});

item.Dump();
var result = JsonPath.Parse("$.*.value").Evaluate(item);
result.Dump();

result.Matches?.SelectMany(n=>n.Location.Segments.Select(n => n.Source)).Dump();
```

Is there a new way to quickly get the hello and value segments from the match?

**Comment by gregsdennis** [comment]
Hey there.  Thanks for the question.

I made that change as the JSON Path working group [decided](https://github.com/ietf-wg-jsonpath/draft-ietf-jsonpath-base/issues/44) to include the path to the match as a JSON Path.  The reasoning was that JSON Path was sufficient and it was unnecessary to introduce a dependency on another, albiet related, technology.

Since then, we have defined that these output paths must be "singular."  That is, they must be represented in such a way as to guarantee that they specify at most a single location within any given JSON document.

Because of the working group's hesitancy to include this dependency in the specification, I also have decided to make sure the same dependency doesn't exist in the libary.

---

That said, I actually do have that logic you're looking for.  It's in the JSON Logic code, and it's fairly straightforward.

https://github.com/gregsdennis/json-everything/blob/e4ed14468a40472739908a876f22f4fbd099e656/JsonLogic/Rules/VariableRule.cs#L33

The primary difference here is that locations in JSON Logic are specified just as dot-delimited paths (e.g. `foo.bar.baz`).  Since they're not quite JSON Path, this code might need a little working out, depending on the path you get.

If I were to include this code in the suite, I'm not really sure where it'd go.  It doesn't really fit in either library.

**Comment by SGStino** [comment]
I'm not seeing where the `Replace('.','/')` comes into play, since the jsonpath would be `$['hello']['value']`? 
 
A simple IEnumerable<string> ToPathElements() in JsonPath would make it compatible with JsonPointer.Create(IEnumerable<string> elements) without the hard-coded dependency, right?

**Comment by gregsdennis** [comment]
> A simple IEnumerable ToPathElements() in JsonPath would make it compatible with JsonPointer.Create(IEnumerable elements) without the hard-coded dependency, right?

Yeah, that's not a bad idea.  I'll take a look and see if there's a way to expose something that that makes sense.

**Comment by gregsdennis** [comment]
> you can convert all pointers to paths

This isn't necessarily true.  The pointer `/foo/1/bar` could be either `$['foo'][1]['bar']` or `$['foo']['1']['bar']`.  These will give different results based on the data you're querying.

**Comment by gregsdennis** [comment]
The specification is introducing the idea of a "singular path" which is a path that points to a specific location.  This subset of paths can be converted to pointers.

In [making some updates](https://github.com/gregsdennis/json-everything/pull/362) I've removed the reference to JsonPointer.Net.  I might add an extension method that outputs a string version of a pointer that can then be parsed into the `JsonPointer` model, but I want to keep the libraries independent.

**Comment by gregsdennis** [comment]
An interesting aspect of this is that it seems JSON Pointer supports basically all of Unicode in its strings without escaping.  The only escapes it mentions are for `~` and `/`.  But JSON Path requires that many chars be surrogate-pair-encoded, like JSON does.

Adding this to #372 as a bonus.
