### ISSUE TITLE
JsonLogic v3.1.0 breaks null checks

### ISSUE THREAD

**Issue by jhspinpanel** [gregsdennis/json-everything#313]
**Environment**
- Nuget Package: JsonLogic
- Nuget Version: 3.1.0
- OS: Windows 11 64 Bit
- .Net Target: .net core 3.1

**Describe the bug**
Operations like "!=", "==" and possible more against or with null are broken after upgrading to v3.1.0. They were working in v3.0.0
See the code snipped in the "To Reproduce" section for an example. The code there throws an exception like this:

```
Object reference not set to an instance of an object.
   at Json.Logic.Rules.LooseEqualsRule.Apply(JsonNode data, JsonNode contextData)
   at async Program.<Initialize>(?) in :line 17
   at Program.<Main>()
```

**To Reproduce**
Code to reproduce in RoslynPad or the likes:

```csharp
#r "nuget:System.Text.Json/6.0.5"
#r "nuget:JsonLogic/3.1.0"

using System.Text.Json;
using System.Text.Json.Nodes;
using Json.Logic;

var node = JsonNode.Parse(@"
{
        ""=="": [
            {""var"": ""value""},
            null
        ]
}");

var rule = System.Text.Json.JsonSerializer.Deserialize<Rule>(node.ToJsonString());
rule.Apply(JsonNode.Parse("{\"value\": null}"));
```

**Expected behavior**
The `.Apply()` call should return true for the test case

**Additional context**
The issue doesn't exist in v3.0.0 but in 3.0.0 other things are broken therefore we've upgraded to 3.1.0

**Comment by gregsdennis** [comment]
Thanks for the report. This seems to be related to say least another issue.

I'll dig in tonight.

**Comment by jhspinpanel** [comment]
> Thanks for the report. This seems to be related to say least another issue.
> 
> I'll dig in tonight.

Thanks, if you need anything let me know. I'm located in Europe and my day just started :)

**Comment by gregsdennis** [comment]
Minor suggestion:  the `.ToJsonString()` isn't necessary.  `JsonNode` has a deserialization extension method on it that lets you change 

```c#
var rule = System.Text.Json.JsonSerializer.Deserialize<Rule>(node.ToJsonString());
```

to

```c#
var rule = node.Deserialize<Rule>();
```

---

I've replicated the issue, though.  Continuing to dig.

**Comment by gregsdennis** [comment]
Okay.  Props to the .Net team for anticipating this one.

By default, the serializer skips the JSON converter for reference types when the value is `null` and just "deserializes" a null.  This was causing the arguments for the `==` rule to deserialize (expecting a `Rule[]`) to `[ <VariableRule>, null ]`, and I couldn't handle it in the `Rule` converter (because it was being skipped).

But they put in a virtual property on the converter base called `HandleNull`.  I've set this to true, and now the `Rule` converter can handle the `null` and coerce it to another `VariableRule` with a null value.

This fixes the issue of throwing the exception, and the rule now returns `true`.

I'll have an update out shortly.

**Comment by jhspinpanel** [comment]
Thanks a lot! We really appreciate your efforts and especially the very quick turn-around time. It has been a pleasure using your libraries
![MotiHeartsGIF](https://user-images.githubusercontent.com/67051605/183045355-ef050d03-6b1c-4c48-816f-f9bc9a3ca79f.gif)
