### ISSUE TITLE
JSON Schema Validation: Exception thrown when object contains multiple values with same name

### ISSUE THREAD

**Issue by MCD-WD** [gregsdennis/json-everything#324]
Environment: VS2022, Windows 10, .Net 6.0, 

Version: json.schema.dll 3.1.1.0, 3.2.0 (found with 3.1.1, upgraded, confirmed exists with 3.2.0.)

If I try to validate a data file with the same value in an object twice, the validation throws an exception. The schema is written a little strangely so it's possible that's related.

Example:

`{ "code": "123", "code": "456" }`

I have an older tool with .Net 4.8 using version 1.10.6.0 and it doesn't work great (output is not highly intelligible) but it's not throwing an exception.

Note - I realize that this isn't legal JSON, I'd just like it to not throw an exception and instead have some vaguely intelligible output.

Attached files: 
- data.json.txt - JSON data file with "code" duplicated near the bottom.
- schema.json.txt - JSON schema file. It does that weird thing with min/max because one of the validators we use doesn't deal with things named "type" properly.
- Exception.txt - exception thrown
- v1_10_6_0.txt - output from validation with json.schema.dll 1.10.6.0.

[Exception.txt](https://github.com/gregsdennis/json-everything/files/9404193/Exception.txt)
[data.json.txt](https://github.com/gregsdennis/json-everything/files/9404319/data.json.txt)
[schema.json.txt](https://github.com/gregsdennis/json-everything/files/9404341/schema.json.txt)
[v1_10_6_0.txt](https://github.com/gregsdennis/json-everything/files/9404369/v1_10_6_0.txt)

**Comment by gregsdennis** [comment]
The specification addresses this in [section 4.2.1](https://json-schema.org/draft/2020-12/json-schema-core.html#section-4.2.1)

> Since an object cannot have two properties with the same key, behavior for a JSON document that tries to define two properties with the same key in a single object is undefined.

This isn't exactly a bug.  JSON itself doesn't regard duplicate keys as an error, but many parsers do, including System.Text.Json's `JsonObject`.

Unfortunately `JsonObject` doesn't throw an exception until you try to access the data.  It does this because of an internal delayed parse.  (Please see my open issue https://github.com/dotnet/runtime/issues/71784.)

All of that said, JSON Path and JSON Logic decree that evaluation-time errors MUST NOT occur, which means I had to create [an extension method](https://github.com/gregsdennis/json-everything/blob/master/Json.More/JsonNodeExtensions.cs#L205) for accessing objects to account for the potential for duplicate keys, wrapping the access in a try/catch.  The problem is that running an operation through a try/catch is generally quite expensive, especially when that operation is object member access.

I'd prefer not to add that overhead to JSON Schema.

**Comment by gregsdennis** [comment]
> I have an older tool with .Net 4.8 using version 1.10.6.0 and it doesn't work great (output is not highly intelligible) but it's not throwing an exception.

That version is based on `JsonElement` rather than `JsonNode`.  This is probably the difference that you see.

**Comment by MCD-WD** [comment]
I have to admit I'm only understanding maybe 25% of what you said a couple comments up. Far from my area of expertise (not that I'm sure I have an area of expertise.)

My problem is I'm not sure how to handle it up at the application level and get it to output something reasonable, and I assumed you were "close" enough to have a better idea of what happened. 

Unless you have a better suggestion, I guess I'll just put in a catch for the annoyingly general exception type ("ArgumentException") and hope for the best. This is just a tool for our testing team anyway.

Something like:

  ```
catch(System.ArgumentException sae)
{
    if (sae.Source == "System.Text.Json")
    {
         Console.WriteLine($"{dataFileBaseName}\tFail - possibly a duplicate key named \"{sae.ParamName}\". Exception \"{sae.Message}\"");
    }
    else
    {
        Console.WriteLine($"{dataFileBaseName}\tException ArgumentException \"{sae.Message}\"");
    }
}
  
```

**Comment by gregsdennis** [comment]
I agree that it's not the ideal solution, but I think a single overarching try/catch will perform better in the end.

If you have control of the data you're validating, I suggest trying to fix the duplicate keys issue at the source before you validate it.

If the data is coming from an external source, having a pre-process step of iterating over the data might be able to ensure that it's in a good state.  That shouldn't be very expensive.

In either case, I think failing earlier will give you a better idea of what's going on.

**Comment by MCD-WD** [comment]
The tool I'm building is for our test team to validate data coming in from vendors in our test environment, so I just need to be able to say something vaguely sensible for them to bounce it back to the vendor development team. .

I'm running against my "test library" of around 50,000 files and only found one instance of it (and that was probably a manual edit error.) It just seemed like being a "good user" to mention it.
