### ISSUE TITLE
NullableAttribute not checked for in cache

### ISSUE THREAD

**Issue by jnystad** [gregsdennis/json-everything#325]
**Environment**
- Nuget Package: JsonSchema.Net.Generation 
- Nuget Version: 3.0.2 
- OS: Linux (WSL Ubuntu) 
- .Net Target: 6.0 

**Describe the bug**

NullableAttribute by default has no IAttributeHandler (it is instead handled in NullabilityRefiner) and is therefore ignored in WhereHandled filter in SchemaGenerationContextCache.Get() used to calculate hash.

**To Reproduce**

Have several members of same type but only some with Nullable attribute. The non-nullable members may be "infected" with null.

**Expected behavior**

Nullable should be included in list of attributes passed to CalculateHash to ensure different hash.

**Additional context**

Possible fix is adding IAttributeHandler to NullableAttribute with an empty implementation.

**Comment by gregsdennis** [comment]
Interesting find.  This may have crept in when I allowed `[Nullable]` to be applied to types instead of just members.  I don't think I intended this attribute to be used on types, and this may be a mistake.  I definitely don't have any tests for that use case.

Do you have the attribute on a type or just on members?

**Comment by jnystad** [comment]
I have only tested it on members.

In general, this applies to any attribute that is only handled in refiners, and not attribute handlers. So perhaps there should be a way to indicate that attributes affects type info in some way. Otherwise, adding an empty IAttributeHandler for the offending attribute seems to be a manageable workaround for now.

**Comment by gregsdennis** [comment]
Okay.  I see what's happening now.  (You're right, but I had to follow it in the code to see it.)

When I process a type, I also consider the attributes.  However, I don't want to consider attributes that I don't care about (e.g. `[JsonConverter]`), so I have a `.WhereHandled()` extension method that filters out those attributes.  The current implementation of `.WhereHandled()` is written to only care about attributes that implement `IAttributeHandler` or have a handler registered.  Since neither of these apply to `[Nullable]`, having a reference type with `[Nullable]` matches the same cache entry as that type without `[Nullable]`.

This is what causes the contamination across properties and why the workaround fixes it.

I'll update `[Nullable]` to implement `IAttributeHandler` as a no-op so that it's just included by default.  I'll also need to update the docs.

**Comment by jnystad** [comment]
Thanks!
