### ISSUE TITLE
Custom keywords are not validated

### ISSUE THREAD

**Issue by mirkoSekulic** [gregsdennis/json-everything#340]
**Environment**
- Nuget Package:  JsonSchema.Net
- Nuget Version: 3.2.1
- OS: widows
- .Net Target: .net6

**Describe the bug**

Given that custom keyword is created and registered with SchemaKeywordRegistry.Register method, when validating json schema that contains defined keyword, validation of custom keyword is ignored. Validate method of custom keyword is never called.

**To Reproduce**

- Create Custom keyword in new project that references JsonSchema.Net 3.2.1 package
- Implement validate method
- Generate json schema that contains the custom keyword
- Register custom keyword with SchemaKeywordRegistry.Register method
- Run validate method on generated json schema

**Expected behavior**

Validate method of custom keyword should be called when validating json schema.

**Additional context**

**Comment by gregsdennis** [comment]
Thanks for reporting. I can look into it more deeply next week, but initial thoughts are that you may need to include it in a custom vocab.  You _shouldn't_ need to, but that may be the bug.

**Comment by mirkoSekulic** [comment]
Are there any updates on this issue?
Seems like registering custom vocabulary doesn't make any difference.

**Comment by gregsdennis** [comment]
I'm sorry. I've been moving house. I should have time next week as that's settled down quite a bit.

**Comment by gregsdennis** [comment]
I've had a look at this and determined what's going on.

There are two filtering stages that occur during validation.

- filter by draft - ensures that things like `$dynamicRef`, a 2020-12 keyword, aren't processed in a draft 7 schema
- filter by vocab - ensures that only keywords that are declared by the vocabs in the meta-schema (if there are any) are processed.

To pass the first filter, you need to have a `[SchemaDraft()]` attribute on your keyword with the draft(s) it should be compatible with, e.g. `[SchemaDraft(Draft.Draft201909 | Draft.Draft202012)]`.  (If you're using draft 6 or 7, this is all.  Do this and stop reading. 😄)

To pass the second filter, however, is a bit more complex, and I suspect this one may be what's tripping you up.  Since 2019-09 and 2020-12(and any future versions) have the vocabulary system, the library is more strict on what gets through.  These JSON Schema versions push people to use the vocabulary system to extend schemas rather than merely defining a keyword.  This involves:

- creating a keyword
- creating a vocabulary that declares that keyword
- registering the keyword
- registering the vocab

That's a lot of boilerplate for adding a custom keyword that maybe you're only using internally.

The idea of vocabularies is (and it's still a system that in development a bit) that a schema that declares a custom keyword does so because it wants that keyword to be processed.  To try and guarantee that, the spec requires that implementation must understand the vocabulary that declares the keyword.  If it doesn't, then the implementation must refuse to process the schema entirely.  A consequence of that is that the implementation also _only_ processes the keywords that are declared by the vocabularies present in the meta-schema.

From what I can see, my options are:

- create an option to circumvent this requirement and allow custom keywords (default would be off)
- create an extension method that creates an ad-hoc vocabulary and meta-schema

The problem with the second one is that your schema would have to use that meta-schema, which means you'd have to modify the `$schema` after deserialization, and schemas are immutable (by design).

**Comment by gregsdennis** [comment]
@mirkoSekulic v3.3.0 adds an option called `ProcessCustomKeywords`.  Set this to true to process your keywords.

**Comment by mirkoSekulic** [comment]
@gregsdennis works great now. Thanks!
