### ISSUE TITLE
Validating against a schema with patternProperties fails

### ISSUE THREAD

**Issue by KarloX2** [gregsdennis/json-everything#341]
**Environment**
- Nuget Package: JsonSchema.Net
- Nuget Version: 3.2.1
- OS: Windows
- .Net Target: .NET 6

**Describe the bug**

Hi there,

I have this schema:

```
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "type": "object",
  "properties": {
    "Items": {
      "type": "object",
      "propertyNames": {
        "minLength": 1,
        "maxLength": 20
      },
      "patternProperties": {
        "": {
          "type": "object",
          "properties": {
            "RemoteIpAddress": {
              "type": "string",
              "oneOf": [
                { "format": "ipv4" },
                { "format": "ipv6" }
              ]
            },
            "RemotePort": {
              "type": "integer",
              "minimum": 1,
              "maximum": 65535,
              "default": 65045
            },
            "Comment": {
              "type": "string"
            }            
          },
          "required": [ "RemoteIpAddress" ]
        }
      }
    }
  },
  "required": [ "Items" ]
}
```

and this document:

```
{
  "Items": {
    "W1": {
      "RemoteIpAddress": "127.0.0.1",
      "RemotePort": 65045
    }
  }
}
```

And when I try to validate that document using `Json.Schema.JsonSchema.Validate()` the resulting ValidationResults has IsValid==false (but no message). However, this schema works fine both in Visual Studio editor and when I try on www.jsonschemavalidator.net

Any clue?
Thanks!

**Comment by gregsdennis** [comment]
Have you tried using another output format?  `Verbose` will give you the most detail and is useful for debugging.

(Please reformat your post to make reading the schema easier.  Three backticks `\`` makes a code block where you can add line breaks.)

**Comment by KarloX2** [comment]
@gregsdennis Thanks.
With the `OutputFormat = OutputFormat.Verbose` I get this:

Message: `Expected 1 matching subschema but found 2`
SchemaLocation.Source: `#/properties/Items/patternProperties//properties/RemoteIpAddress/oneOf`

Then I found that after changing the $schema property value in my schema to
```
https://json-schema.org/draft/2019-09/schema
```

it seems to work. Does that make sense to you?

**Comment by gregsdennis** [comment]
Do you have format validation enabled?

**Comment by KarloX2** [comment]
@gregsdennis 
Ok, after setting `RequireFormatValidation = true` in the ValidationOptions I get IsValid=true even with `"$schema": "http://json-schema.org/draft-07/schema"`.

Can you explain that? Thanks

**Comment by gregsdennis** [comment]
Please have a read of the [docs for format validation](https://json-everything.net/json-schema#value-format-validation).  If you have more questions, I can answer them for you.

**Comment by KarloX2** [comment]
@gregsdennis Okay, the only thing I don't quite understand is why the schema of version _2019-09_ would work without that `RequireFormatValidation` switch being set to true, while for _draft-07_ it is needed. Just an implementation detail or does that reflect a change in the specification between the versions?
Anyway it works fine now. Thank you!

**Comment by gregsdennis** [comment]
Specification sections:

- [2020-12](https://json-schema.org/draft/2020-12/json-schema-validation.html#name-vocabularies-for-semantic-c)
- [2019-09](https://datatracker.ietf.org/doc/html/draft-handrews-json-schema-validation-02#section-7)

In 2019-09, validation was controlled by the presence of the format vocabulary and its value in the meta-schema's `$vocabulary` keyword.  A value of `false` meant that only annotations were expected (the value of `format` would be included in the output), whereas a value of `true` meant that vaildation was required.  The catch is that implementations (like this one) were still allowed to validate even when the meta-schema only required annotation, but that functionality must be exposed as a configuration option.

The problem with this approach was that the `true`/`false` value of the vocabulary wasn't intended to change behavior of keywords, but to indicate whether the implementation was required to understand the vocabulary in order to process the schema.

In 2020-12, we fixed this by splitting the format vocabulary into two: one for annotation, and one for validation.  That way the behavior is only dependent upon which vocabulary is used, and the `true`/`false` value can be properly utilized.

The 2019-09 meta-schema has the vocabulary listed with `false`, so only annotations are required by default.  (If you're experiencing that this library is performing such validation, then that's a bug.)  This also had the side effect that if the implementation doesn't know what the format vocabulary is, the `format` keyword could be ignored completely.

The 2020-12 meta-schema as the format-annotation vocabulary listed with `true`, meaning that only annotation collection is required, but the implementation must know what the format vocabulary is to process the schema.

**Comment by gregsdennis** [comment]
I've verified that the library is working as expected.  If you go to https://json-everything.net/json-schema and use:

```json
// schema
{ "format": "ipv4" }

//instance
"literally any string except for an ipv4 address"
```

and set 2019-09 as the spec version, you'll find that the validation passes without "Require `format` validation" and fails with it.

**Comment by KarloX2** [comment]
Thank you very much for your help and the explanations.
