### ISSUE TITLE
JsonSchema.FromFile sets BaseUri incorrectly

### ISSUE THREAD

**Issue by shadow-cs** [gregsdennis/json-everything#35]
**Describe the bug**

`JsonSchema.FromFile` assigns `BaseUri` of the result in a way that produces URI which different resource by not properly handling characters which should be escaped.

https://github.com/gregsdennis/json-everything/blob/6f99f55ccedbef159a3bdf556bf24cbd7f6206df/JsonSchema/JsonSchema.cs#L64

**To Reproduce**

Place a schema on a path which has a character which should be escaped.

This is particularly visible if `#` character is present, the part of path after `#` is parsed as `Uri.Fragment` which is not part of a file path when `Uri.LocalPath` (and possibly other properties) is queried.

See https://dotnetfiddle.net/wrWwsw.

**Expected behavior**

`BaseUri` should be set to correctly constructed `Uri`.

**How to fix**

Use the default ctor, it converts absolute paths correctly. This should work on Windows and Linux. 

See https://dotnetfiddle.net/rHWSFJ and https://dotnetfiddle.net/M1ylXS.

Note: Keep in mind, that the usage differs a bit between Windows and Linux, absolute paths on Linux and Windows differ (Linux doesn't begin with a drive letter obviously 😉) so using Linux absolute path on Windows throws an exception, this is expected and correct behavior (I did test on .NET Framework and .NET Core 3.1, I did not test on Mono though).

**Additional context**

Introduced in version`1.4.0`.

**Comment by gregsdennis** [comment]
I'm going to have to do some research on file-based URIs before I do anything.  I'll post relevant links here.

**Comment by gregsdennis** [comment]
[This blog post](https://weblog.west-wind.com/posts/2019/Aug/20/UriAbsoluteUri-and-UrlEncoding-of-Local-File-Urls) seems quite pertinent.  It's the first thing I found, and he does what I'm doing.

However, playing with your fiddle and his, using both Linux and Windows yield an absolute URI without the `file:///` scheme, as you suggest.  But his doesn't work with Linux paths.

I was also surprised to find that `/home/path.json` is an absolute path.

Another thing the blog gets right that I should consider is that the path needs to not be URL-encoded since the system will attempt to re-encode it.  I think this is something that I'll just add to the docs rather than try to force.

**Comment by gregsdennis** [comment]
I'm pushing out v1.5.1.  Please close if that resolves this issue for you.

**Comment by shadow-cs** [comment]
Works in my case, please consider adding `baseUri` to `FromText` and `FromStream` as well, it could be used if fetching schema from the web (in case it doesn't use `$id`) or from other sources (resource or an archive).

**Comment by gregsdennis** [comment]
I think I'm going to leave the other two as they are.  The options expose a `DefaultBaseUri` now.
