### ISSUE TITLE
Filter not empty string properties

### ISSUE THREAD

**Issue by bard83** [gregsdennis/json-everything#351]
**Environment**
[JsonPath](https://json-everything.net/json-path/)

**How can I help you today?**

Is there a way to filter simply saying that the X properties should exist and not be null or empty without check the values programmatically?

**Additional context**

Applying  the following expression `$.[?( @.a && @.a != null && @.a != '')]` (Test1) to the below samples,  does not return the first element as result, but just an empty result. Probably `@a` statement is too strict or just redundant, so it has been removed it and tested like this `$.[?(@.a != null && @.a != '')]`  which returns a totally unattended result (see below Test2).  Funny fact is that this `$.[?( @.a != null && @.a == '')]` (Test3) works like expected. It seems to me that this  `$.[?( @.a != '')]` (Test4) does not do what I expect to do or just I'm miss-interpreting the results.

Sample:
```json
[
    {
        "a": "value"
    },
    {
        "a": ""
    },
    {
        "a": null
    },
    {
    }
]
```

**Test1**

Expression: `$.[?( @.a && @.a != null && @.a != '')]`
Result

```json
[]
```

Expected
```json
[
  {
    "Value": {
      "a": "value"
    },
    "Location": "$[0]"
  }
]
```

**Test2**

Expression: `$.[?(@.a != null && @.a != '')]`
Result

```json
[
  {
    "Value": {
      "a": "value"
    },
    "Location": "$[0]"
  },
  {
    "Value": {},
    "Location": "$[3]"
  },
  {
    "Value": "value",
    "Location": "$[0]['a']"
  },
  {
    "Value": "",
    "Location": "$[1]['a']"
  },
  {
    "Value": null,
    "Location": "$[2]['a']"
  }
]
```

Expected

```json
[
  {
    "Value": {
      "a": "value"
    },
    "Location": "$[0]"
  }
]
```

**Test3**

Expression: `$.[?( @.a != null && @.a == '')]`
Result

```json
 [
  {
    "Value": {
      "a": ""
    },
    "Location": "$[1]"
  }
]
```

Expected

```json
[
  {
    "Value": {
      "a": ""
    },
    "Location": "$[1]"
  }
]
```

**Test4**

Expression: `$.[?(@.a != '')]`
Result

```json
[
  {
    "Value": {
      "a": "value"
    },
    "Location": "$[0]"
  },
  {
    "Value": {
      "a": null
    },
    "Location": "$[2]"
  },
  {
    "Value": {},
    "Location": "$[3]"
  },
  {
    "Value": "value",
    "Location": "$[0]['a']"
  },
  {
    "Value": "",
    "Location": "$[1]['a']"
  },
  {
    "Value": null,
    "Location": "$[2]['a']"
  }
]
```

Expected

```json
[
  {
    "Value": {
      "a": "value"
    },
    "Location": "$[0]"
  }
]
```

**Comment by gregsdennis** [comment]
All of your examples have `$.[]` (notice the dot).  This is invalid JSON Path.  Just remove the dot.

```
$[?(@.a != null && @.a != '')]
```

gives

```json
[
  {
    "Value": {
      "a": "value"
    },
    "Location": "$[0]"
  },
  {
    "Value": {},
    "Location": "$[3]"
  }
]
```

I do seem to have a bug around the existence test `@.a` being combined with another check with the "and" `&&`.

As mentioned in #350, this library is still in initial stages while the spec is being written, and my focus has been JSON Schema so I haven't had much time to work on it.

---

I'm not sure about some of your expected results, though.

### Test 2

```
$[?(@.a != null && @.a != '')]
```

should (and does) give

```json
[
  {
    "Value": {
      "a": "value"
    },
    "Location": "$[0]"
  },
  {
    "Value": {},
    "Location": "$[3]"
  }
]
```

This is because `@.a` on `{}` evaluates to an "undefined" which isn't `null` and isn't `''`.

### Test 4

```
$[?(@.a != '')]
```

should (and does) give

```json
[
  {
    "Value": {
      "a": "value"
    },
    "Location": "$[0]"
  },
  {
    "Value": {
      "a": null
    },
    "Location": "$[2]"
  },
  {
    "Value": {},
    "Location": "$[3]"
  }
]
```

for the same reason as above.

**Comment by bard83** [comment]
Thanks for the explanation. 

> All of your examples have $.[] (notice the dot). This is invalid JSON Path. Just remove the dot.
> `$[?(@.a != null && @.a != '')]`

In this case I don' t understand why the expression  is not reject as not valid (?).

> I do seem to have a bug around the existence test `@.a` being combined with another check with the "and" &&.

I'll open a bug for it, and try to provide a PR if I find the time.

**Comment by gregsdennis** [comment]
> In this case I don' t understand why the expression is not reject as not valid (?).

The issue is that it's accepting an empty string property name.  Then the empty string matches on all properties for some reason. It's a bug.

No need to open a new bug. All this can be tracked here.

I'll fix it when I can in conjunction with updates that we're making to the spec.

In the meantime, maybe look at JsonCons, linked in this project's readme.

**Comment by bard83** [comment]
Ok, thanks.
