### ISSUE TITLE
More examples for vocabulary/data

### ISSUE THREAD

**Issue by sandrina-p** [gregsdennis/json-everything#391]
Based on https://github.com/gregsdennis/json-everything/issues/377, I found out that `json-everything` also supports operations similar to JsonLogic.

Could you add more examples to the docs of what's possible to be validated?

Thank you :)

**Comment by gregsdennis** [comment]
> `json-everything` also supports operations similar to JsonLogic.

This project _fully_ supports JsonLogic, not just operations similar to it.  There are some alignment issues due to the incompleteness of their "spec" (it's just a web page) that require experimentation that I just don't have time for right now.  That what #377 is.

> Could you add more examples to the docs of what's possible to be validated?

I can.  The vocabulary itself has a simple example, and there are several others in the [vocab test suite](https://github.com/gregsdennis/json-schema-vocab-test-suites/tree/main/tests/data).  I can make some fuller examples for the site.

**Comment by gregsdennis** [comment]
If you have specific use cases you'd like to see, please let me know.  Otherwise, I'll draw from the test suite and StackOverflow questions I've seen.

**Comment by gregsdennis** [comment]
I've added a few, but I can't think of a legit reason to reference the schema off the top of my head.  I've seen requests for it before; they're just slipping my mind.

**Comment by sandrina-p** [comment]
The repo you linked [vocab-test-suites](https://github.com/gregsdennis/json-schema-vocab-test-suites/tree/main/tests/data) is a great start for me to look for examples. In the next weeks, I'll continue exploring this feature and if I have a particular question, I'll ask it here :)

Thanks @gregsdennis !

**Comment by sandrina-p** [comment]
Hi again @gregsdennis, do you mind me doing a follow-up question:

> This project fully supports JsonLogic, not just operations similar to it. 

What do you mean by fully supporting it? 

For instance, if I want to say "a is twice as big as b"... How would I do that validation with `json-everything`?

Here's how we would do it with jsonLogic:

```json
{ ">": [
    { "var": "a" },
    {"*": [{ "var": "b" }, 2]}
]}
```

Which, would result in the following:

```json
// true
{ "a": 11, "b": 5 }

// false
{ "a": 9, "b": 5 }
```

You can test it [in their playground](https://jsonlogic.com/play.html), here's a screenshot: 
<img width="1084" alt="image" src="https://user-images.githubusercontent.com/14869087/223211782-f741b443-1101-49dc-99c1-34b5ba47c0cb.png">

**Comment by gregsdennis** [comment]
JSON Logic isn't validation, it's processing.  It just happens that you're using that processing to do a little creative validation.  You can use my JsonLogic library to do the same thing in .Net.  It works on my playground as well.

<img width="694" alt="image" src="https://user-images.githubusercontent.com/2676804/223216998-37bca882-cfd0-4e3f-9e27-28f33ace449c.png">

What you're asking for isn't possible with JSON Schema, even with my `data` vocabulary.  I've added an [example](https://json-everything.net/json-schema#example-schemadata-comparative) to show what _is_ possible.  The mathematical operations are what isn't supported.

**Comment by sandrina-p** [comment]
TIL about the concepts of "validation" vs "processing". I haven't realized that difference yet.

Exactly, I'm looking for ways to include "mathematical operations" in validations for JSON Schemas. If you know of any tool/discussion about the topic that you could point me to, I'd highly appreciate it.

**Comment by gregsdennis** [comment]
If you want to have those kinds of features added, I suggest you write up a proposal for them in the [JSON Schema Vocabularies repo](https://github.com/json-schema-org/json-schema-vocabularies).

**Comment by sandrina-p** [comment]
Thanks, Greg, I've been reading that repo quite a lot in the last few days 😅 

Regarding the concepts "validation" and "processing", could you enlight me on what's the difference between validation and processing? The way I found JsonLogic is really looked at as a "validation" tool, as the website says "Build complex rules (...) If you’re looking for a way to share logic...".

**Comment by gregsdennis** [comment]
JSON Logic is built specifically to handle the operations you want, and it does more than just return a true/false result.  You can use it to return all kinds of results.  Have a look at the [`missing_some`](https://jsonlogic.com/operations.html#missing_some) rule to see this.

JSON Schema does validation (and annotation).  It won't modify data or give you new data back.

The purposes are different.  You _can_ use JSON Logic for validation, but its purpose is bigger.

Another major difference is that JSON Schema actually has a specification, not just a website and a few implementations.  Further, JSON Logic does a lot of non-interoperable things because it was originally written in JS and PHP, which aren't as strict on typing as a lot of other languages.  I've had to jump through serious hoops to get it to work, and it's still not aligned.

**Comment by sandrina-p** [comment]
I really appreciate your summary on each one of the tools @gregsdennis. I will keep that in mind for my research. Thank you :)
