### ISSUE TITLE
Get (valid!) JsonPath or JsonPointer from a JsonNode

### ISSUE THREAD

**Issue by amis92** [gregsdennis/json-everything#406]
**Environment**
- Nuget Package: JsonPath.Net
- Nuget Version: 0.4.0
- OS: dotnetFiddle/Linux
- .Net Target: 

**Can this library make doing something simpler?**

I'd like to be able to generate a correct JSON Path and/or JSON Pointer from a System.Text.Json.Nodes.JsonNode type.

**Describe alternatives you've considered**

Post a bug report to dotnet/runtime.

**Additional context**

Json path generated by BCL's `JsonNode.GetPath()` for a property like `$id` is invalid and fails to be parsed by JsonPath.

I'd like to have some (extension?) methods that provide a valid JsonPath and JsonPointer given a JsonNode. It seems to already be mostly done within the code of this library, but is not available via public API. It can return a plain string, or a strongly typed parsed instance of path or pointer.

A dotnet fiddle to illustrate the issue: https://dotnetfiddle.net/vkcQQ8

**Comment by gregsdennis** [comment]
Thanks for reporting.  Can you provide an example of a path that's invalid?

Note that the `JsonNode` path is the node's position within it's current tree, starting from the tree root node.  (Really they should be using JSON Pointer, as you suggest.)

This particular library is in line with the new JSON Path spec that I'm helping develop (there's a link in the readme).  There are some differences with traditional JSON Path, so what comes out of `JsonNode` may not completely align.  Hopefully once the spec is finalized, others will update to implement it.

I'll open an issue with dotnet urging them to adopt the spec once it's released, but I wouldn't expect any changes until it is.  Even then, the dotnet team is extremely averse to changing things that remove previous support.

Unfortunately I can't really do much more than that since I'm not on that team.

**Comment by amis92** [comment]
Right, it's in the linked fiddle, but I'll show:

Given
```json
{"$defs":{"foo['bar":"baz"}}
```

When `JsonNode.GetPath()` is called on the root node, it returns `$.$defs['foo['bar']`. That is unparseable whatever you'd try to do.

I know that the spec is still not final, and I also know that `GetPath()` is a convenience from .NET team, because it's not used internally anywhere, but the same internal implementation is used for generating paths for Json De/Serialization exceptions - and that again is not going to be parsed by any machine anyway. So the problem on their side is not big.

What I'd love to be able to do is (given a `JsonNode`) create a spec-compliant path with the `Json.Path` (and pointer with `Json.Pointer`) - right now there's only a Parse API (and that doesn't work very well with the bad paths from BCL's GetPath).

**Comment by gregsdennis** [comment]
Some related issues already on the dotnet team's radar:

- https://github.com/dotnet/runtime/issues/31068
- https://github.com/dotnet/runtime/issues/56592 (tangentially related)

**Comment by gregsdennis** [comment]
I think what you've discovered is a true bug in that they're not considering character escaping needs.  I think their focus is serialization, which means they're really only considering .Net-valid property names.

**Comment by gregsdennis** [comment]
@amis92 can you add a comment to☝️ with any environmental details, please?

**Comment by amis92** [comment]
I don't have much to add, however seeing as you wrote that the Expected Output was `$.$defs['foo[\'bar']` I'm wondering if there shouldn't be some more "loose" mode for `JsonPath.Parse(string)` in this library here - it fails even for `JsonPath.Parse("$.$defs")` - is that expected?

**Comment by gregsdennis** [comment]
good point.  The `$defs` isn't valid as shorthand.  I'll update that issue.

**Comment by gregsdennis** [comment]
To be clear, I could probably create an extension that could do this right, but I'd prefer that dotnet fix their implementation.  I'll wait to see what they say.  If they're unwilling to change, I'll create that extension in Json.More.Net.

**Comment by gregsdennis** [comment]
They've added it to the "Future" milestone.  I don't think it's gonna get done any time soon.  I might have a look at creating an extension.
