### ISSUE TITLE
Guidance on how to validate a schema with many $ref against a HTTP response

### ISSUE THREAD

**Issue by mattferderer** [gregsdennis/json-everything#411]
**Environment**
- Nuget Package: 3.2.0
- OS: Windows & Linux
- .Net Target: .NET 7

**How can I help you today?**

I'm looking to use JsonSchema to test Open API (Swagger) JSON data contract files against our API.

I'm submitting a HTTP GET request & looking to compare the response body against our Open API json file to see if the response is valid against the json schema defined.

Our schema file will sometimes have something like this with many nested $ref:

```json
"paths": {
    "/Cars": {
      "get": {
        "summary": "Get List of Cars",
        "responses": {
          "200": {
            "$ref": "#/components/responses/CarData"
          }
        }
      }
    }
  },
  "responses": {
      "CarData": {
        "description": "Collection of Cars",
        "content": {
          "application/json": {
            "schema": {
              "type": "object",
              "properties": {
                "value": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/Car"
                  }
                }
              }
            }
          }
        }
      },
   },
   "components": {
    "requestBodies": {},
    "schemas": {
      "Provider": {
        "type": "object",
        "examples": [],
        "description": "Single Provider ",
        "title": "Provider Response",
        "properties": {
          "Model": {
            "type": "string",
          },
          "Year": {
            "type": "string",
          },
          "Make": {
            "type": "string",
          },
       },
       "required": ["Model", "Make"]
   }
 }
```

Any suggestions on how to accomplish this would be greatly appreciated.

**Comment by gregsdennis** [comment]
Thanks for the question.  There are a couple things going on here:

1. Only OpenAPI v3.1 supports JSON Schema properly.  Prior versions are an altered version of JSON Schema based on Draft 4 (which this library doesn't support.
2. v4 of JsonSchema.Net introduces the ability to resolve references in arbitrary documents.  This was added specifically to support things like OpenAPI documents which contain references that are relative to the document root rather than the schema root.

For point 2, you may be interested in PR #360 which added this ability.  There are some comments I included for some people over at OpenApi.Net that give basic instructions on how to use this feature.  Also take a look at the [docs](https://json-everything.net/json-schema#schema-embedded-schemas).

**Comment by mattferderer** [comment]
Thank you. That's incredibly helpful. We are using 3.1. I am testing out the preview build & reading through #360 to try & get it to work.
