### ISSUE TITLE
Async `Fetch` in `SchemaRegisty`

### ISSUE THREAD

**Issue by YaroslavKormushyn** [gregsdennis/json-everything#416]
**Environment**
- Nuget Package: JsonSchema.Net
- Nuget Version: 4.0.0
- OS: Windows
- .Net Target: net6.0

**Can this library make doing something simpler?**
I'd like to be able to set the `Fetch` method on the `SchemaRegistry.Global` object to an async lambda in order to resolve external schema references on the fly.
Our referenced schema is located at a public URL. The optimal way of querying the schema would be an `HttpClient`, but the querying itself is asynchronous. The `Fetch` method currently requires the `Func` instance to be synchronous, which renders it unusable for this scenario.

**Describe alternatives you've considered**
We have a workaround of having an initializer method, which gets called on application startup. It registers external schemas in the registry from a known set of schema URLs.
This, however, limits which schemas we support, since any new schema references, which are not present in the list, are not getting resolved.

**Additional context**
We have a base schema on our custom URL, but it cannot automatically resolve.

**Comment by gregsdennis** [comment]
Hey, thanks for the suggestion.  I've tried to do this several times, but I haven't been able to do it in a way that doesn't cause the `async` to rise all the way to the `Evaluate()` method.

I _have_ wanted to make some aspects of evaluation async, but some significant memory usage optimizations I made a few versions ago would have to be undone.  I'll need to investigate ways to adjust things so that I don't lose that.

The workaround I suggest is just accessing the `.Result` property on the `HttpClient` call (which returns a task).  It'll work in most contexts, but might have some issues in others.  For example, Blazor doesn't allow you to access that property.

**Comment by amis92** [comment]
I'd suggest (as a workaround) using the basic [`HttpClient.Send`](https://learn.microsoft.com/en-us/dotnet/api/system.net.http.httpclient.send?view=net-7.0#system-net-http-httpclient-send(system-net-http-httprequestmessage)) method which is synchronous/blocking and doesn't involve async/await/Task.Result - it's implemented as a blocking call all the way through. It's not pretty (requires you to build and pass `HttpRequestMessage` manually), but also not too complicated.

**Comment by gregsdennis** [comment]
> I'd suggest (as a workaround) using the basic [HttpClient.Send](https://learn.microsoft.com/en-us/dotnet/api/system.net.http.httpclient.send?view=net-7.0#system-net-http-httpclient-send(system-net-http-httprequestmessage)) method which is synchronous/blocking and doesn't involve async/await/Task.Result

I thought about using this to enable fetching support for https://json-everything.net/json-schema, but it's explicitly unsupported for some reason:

```c#
[UnsupportedOSPlatform("browser")]
public HttpResponseMessage Send(HttpRequestMessage request) { ... }
```

I am sad.

**Comment by amis92** [comment]
Yeah, for the browser neither `Send` nor `SendAsync.Result` will work. It's because WASM is single-threaded and browser's `fetch` is very explicitly a promise/async, so the .NET cannot even attempt to simulate blocking on it (or they chose not to).

**Comment by gregsdennis** [comment]
This may be of interest here.

As mentioned before I've tried to make things run async several times.  I tried this morning, combining with a new approach to collect contraints so that they could all be run in parallel.  ([changes](https://github.com/gregsdennis/json-everything/commit/bde8a7f46f27b3ce25f6dbb7828ffe5c08ac3752))

Here are the benchmark results:

|                Method |          Mean |        Error |       StdDev |       Gen0 |       Gen1 |     Gen2 |    Allocated |
| ---------------------: |--------------:|-------------:|-------------:|-----------:|-----------:|---------:|-------------:|
|     AsyncConstraints1 |      45.35 us |     0.892 us |     2.031 us |     6.8359 |          - |        - |     13.92 KB |
|   AsyncConstraints100 |   2,439.07 us |    28.515 us |    45.228 us |   453.1250 |          - |        - |    909.75 KB |
| AsyncConstraints10000 | 301,177.23 us | 3,847.724 us | 3,599.164 us | 45000.0000 |          - |        - |  90642.09 KB |
|         SyncEvaluate1 |      28.13 us |     0.425 us |     0.376 us |    10.0708 |     3.3569 |   0.0610 |     20.61 KB |
|       SyncEvaluate100 |   2,203.29 us |    22.325 us |    17.430 us |   773.4375 |   386.7188 |   7.8125 |   1581.24 KB |
|     SyncEvaluate10000 | 214,292.29 us |   877.681 us |   685.236 us | 77000.0000 | 38000.0000 | 500.0000 | 157642.53 KB |

Each iteration runs this validation:

```jsonc
// schema
{
  "allOf": [
    { "maximum": 10 },
    { "minimum": 0 }
  ]
}

// instance
11
```

I ensured that there was no shortcutting in the sync runs (`/allOf/0` fails, so `allOf` could skip the second subschema).

I see there is less memory used in the async version, but it's not fully implemented either (it's not collecting annotations or tracking any of the locations required by output, etc).  What really concerns me is that the async version takes almost twice as long to run.  And it's not fully implemented, either!

I may set up another branch where the _only_ thing I change is making `.Evaluate()` async, but benchmarking that might be hard since it's a code change, not an addition (I can't run both versions).
