### ISSUE TITLE
Errors list is not getting populated in any of the format.

### ISSUE THREAD

**Issue by akshay-zz** [gregsdennis/json-everything#438]
**Environment**
- Nuget Package:  JsonSchema.Net
- Nuget Version: 4.0+
- OS: Windows
- .Net Target: .Net 6.0

**Describe the bug**
In case when the validation fails. The error list is not getting populated. Also, the `HasError `error is not showing as `true`. This behavior started after upgrading to` 4.0.0`. Although IsValid is showing the correct status.

**To Reproduce**
Compare any invalid data against a valid schema.

**Expected behavior**
It should mark the `HasError ` as `true `and also it should populate the `Errors ` list with the validation errors in the case the validation fails.

**Additional context**
None

**Comment by gregsdennis** [comment]
Can you provide an example of what you're running, and the output you expect, please?

**Comment by akshay-zz** [comment]
**Schema**
```
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": { "isWinterLivestockType": { "type": "boolean" } }
}

```
**Invalid Data**
`{ "isWinterLivestockType": 1 }`

In Playground it is showing the errors.
```
{
  "valid": false,
  "details": [
    {
      "valid": false,
      "evaluationPath": "",
      "schemaLocation": "https://json-everything.net/ee1e060c85",
      "instanceLocation": ""
    },
    {
      "valid": false,
      "evaluationPath": "/properties/isWinterLivestockType",
      "schemaLocation": "https://json-everything.net/ee1e060c85#/properties/isWinterLivestockType",
      "instanceLocation": "/isWinterLivestockType",
      "errors": {
        "type": "Value is \"integer\" but should be \"boolean\""
      }
    }
  ]
}
```

But when you use package 4.0.+. It not showing the errors in the error list. Here even though isValid is coming has false but HasError flag still remains false. Same goes for the Errors. Below is the data I'm getting for my code.
<HTML>
<body>



  | Name | Value | Type
-- | -- | -- | --
  | results.Errors | null | System.Collections.Generic.IReadOnlyDictionary<string, string>
  | results.IsValid | false | bool
  | results.HasErrors | false | bool



</body>
</HTML>

**Comment by gregsdennis** [comment]
How are you calling `.Evaluate()` locally?  The default output mode is `Flag`.  If you want more complex output, you'll need to set that in the options when you call `.Evaluate()`.

**Comment by akshay-zz** [comment]
```
var schema = JsonSchema.FromText(request.Schema);
        var jsonDocument = JsonDocument.Parse(request.Data);
        var results = schema.Evaluate(
            jsonDocument.RootElement,
            new EvaluationOptions
            {
                RequireFormatValidation = true,
                EvaluateAs = SpecVersion.Draft202012,
                OutputFormat = OutputFormat.List,
            });

        if (results.IsValid)
        {
            Console.WriteLine("Valid");
        }
        else
        {
            if (results.HasErrors)
            {
                HandleErrors(results);
            }
        }
```

**Comment by gregsdennis** [comment]
Thanks. I can dig into this tomorrow.  I don't immediately see what's going on.

FYI - the playground is actually running the version posted there, which is the latest.

**Comment by akshay-zz** [comment]
Yep, I'm aware, actually, it broke from version` 4.0.0`. I tested this with the latest version i.e 4.0.6, and it is not showing the correct behavior.

**Comment by akshay-zz** [comment]
Hi @gregsdennis, did you able to look into this?

**Comment by gregsdennis** [comment]
I'm sorry, no.  I've been planning a conference trip today.  I'll look at it first thing tomorrow.

**Comment by gregsdennis** [comment]
Okay.  I think I see the source of the confusion.  `HasErrors` only reports whether that node has errors, not the entire tree structure.  In your case, `results.HasErrors` is false because `results` doesn't actually have any errors.  There's a _nested_ node that does have errors.

I can add a `ContainsErrors` (or something) that would report whether nested nodes contain errors if that would help.  (I'd probably add that as a method, actually.)

A couple more notes:

- `RequireFormatValidation` is not needed here as you don't have any formats (maybe you do on other requests)
- `EvaluateAs` is not needed here since the `$schema` is present.  `$schema` takes precedence, and the default behavior is Draft 2020-12 when the option is unspecified and the schema doesn't have `$schema`.

**Comment by akshay-zz** [comment]
Till 3.x.x we use to have  `NestedResults`. That is used to provide the aggregated result. Is there some aggregated error list now?

**Comment by gregsdennis** [comment]
Release notes for 3.x to 4.0: https://json-everything.net/json-schema#release-schema-4.0.0
Changes in JSON Schema output: https://json-schema.org/blog/posts/fixing-json-schema-output

Please read both of these as they are pertinent to the changes.

- `NestedResults` has been changed to `Details`
- Instead of a nested result for each error, the errors are now collected into an `Errors` property for each node.  There is no aggregation.
