### ISSUE TITLE
Why JsonPath.Segments is internal?

### ISSUE THREAD

**Issue by qt-kaneko** [gregsdennis/json-everything#465]
**Environment**
- Nuget Package: JsonPath.Net
- Nuget Version: 0.6.1
- OS: macOS
- .Net Target: .NET 8.0.100-preview.3.23178.7

**How can I help you today?**
I need to get last path segment name, like:
- `some.test` => `test`
- `some[0].second.test2` => `test2`

As I found I could get it from `Node.Location.Segments[^1].Selectors[0].Name`, but Node.Location.Segments is `internal`.

P.S. NameSelector seems to be internal too, can you make it public?

**Additional context**

**Comment by gregsdennis** [comment]
> Why JsonPath.Segments is internal?

JsonPath.Net was intended to be something of a black box rather than present a model that could be explored.  So really the question should be, "Why is `PathSegment` public?"

However, thinking about this for a while, I'm somewhat on the fence.

Firstly, my other libs do expose the model to some degree.

Secondly, if I expose `JsonPath.Segments` then that really only gets you access to segments, each of which contains a collection of selectors (`ISelector`).  However, the implementations of `ISelector` are all internal, so you're not going to be able to access the information they hold unless I expose those.

That means that I'd have to expose all of the selector types, too.  That could be useful, but I'm _very_ hestitant to expose the filter expression models.

At the very least I'd need to go through everything to ensure they're immutable (at least publicly).

As this is still a 0.* library (until the spec is officially released), there are still things that are changing.  I'll keep this in mind for future updates.  In the meantime, you can try this:

```c#
var pointer = JsonPointer.Parse(myPath.ToPointer());
var lastSegmentName = pointer.Segments[^1].Value;
```

Of course, this will only work if the path is singular.

**Comment by qt-kaneko** [comment]
Thanks for your suggestion. I think it will be too slow in my case, and I have already done it the way I wanted using reflection (and I certainly don't don't want to rewrite it due to my laziness 😁).

I'll add my 5 cents: when I'm creating library I try to expose as most as I can, so programmer can use it if needs to. I understand that this maybe will create problems when updating due to breaking changes if I'd want to refactor something, so this maybe is not the perfect way 😅.

Eventually I'm looking forward to exposing this API, thank you for your awesome library!
