### ISSUE TITLE
Pointer in a referenced schema does not seem to work right.

### ISSUE THREAD

**Issue by nvkgbr** [gregsdennis/json-everything#481]
**Environment**
- Nuget Package: JsonSchema.Net
- Nuget Version: 4.1.5
- OS: Windows 10
- .Net Target: .NET 6

**Describe the bug**
Getting an exception when trying to evaluate a basic local file with a schema which has a reference to another schema which has a pointer in it.

`Json.Schema.JsonSchemaException: 'Cannot resolve base schema from 'file:///.../json-everythingValidationTest/bin/Debug/net6.0/files/schemas/%23/definitions/values''
`

In the URI # gets replaced with %23

**To Reproduce**
I created a really small example project for it: [repo](https://github.com/nvkgbr/JsonShcema.NET-test)

**Expected behavior**
The file gets validated.

I am not sure if I am doing something wrong, or is it a bug in the package.

**Comment by gregsdennis** [comment]
### Short answer

No, the change wasn't reverted.  You need to update 

```c#
SchemaRegistry.Global.Register(new Uri(path), schema);
```

to

```c#
SchemaRegistry.Global.Register(schema);
```

### Long answer

The way you're registering the schemas is causing the [.net root cause](https://github.com/dotnet/runtime/issues/85229) to surface again.

This

```c#
new Uri(path)
```

is the exact problem.  If you want to do rebuild, you need to include the `file:///` URI scheme yourself.  `JsonSchema.FromFile()` (see below) does this for you and automatically sets the base URI on the schema, so when you register it, you only need to pass the schema; the registration will grab the URI from the schema.

https://github.com/gregsdennis/json-everything/blob/2f13ec60841d3c7333ed71134c162465ed678b93/JsonSchema/JsonSchema.cs#L95-L107

**Comment by gregsdennis** [comment]
(I love your profile pic, BTW.  Is that the one that was generated for you, or did you do that on purpose?)

**Comment by nvkgbr** [comment]
Thank you kindly for the detailed answer! :)
Unfortunately, I will only be able to try it on Monday, but I will give you an update about it. 

( Haha, yes, this profile pic was generated :D It is so good that I did not change it since )

**Comment by nvkgbr** [comment]
It is working fine now!
Thank you kindly! 😊
