### ISSUE TITLE
How to generate a schema with a oneOf property?

### ISSUE THREAD

**Issue by Jack-Edwards** [gregsdennis/json-everything#508]
### Nuget Package

JsonSchema.Net.Generation

### Package Version

2.1.0

### What's your question?

I'm wanting to generate a JSON schema using a combination of C# class models and ISchemaGenerator implementations to handle unique types ( e.g., the built-in `DateOnly` type and some classes which are best represented with a `oneOf` property ).

This works well until I try working on the `oneOf` generation.  I'm surprised to see there are implementations for `AnyOfIntent` and `AllOfIntent`, but there is no `OneOfIntent`.  Was this overlooked or is there a different way to approach this?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gregsdennis** [comment]
Thanks for raising the issue.

Firstly, `anyOf` is generally preferred over `oneOf` because `anyOf` can return early whereas `oneOf` has to evaluate all subschema every time.

Secondly, inheritance isn't supported at this time.  There's some [discussion](https://github.com/json-schema-org/vocab-idl/issues/49) happening over at JSON Schema about how this can happen (and I have a blog post coming soon).

For now, you'll need to generate individual schemas and compose them yourself.  It's not ideal, but it's where we are right now.
