### ISSUE TITLE
Parsing schema from string when compiled to NativeAOT with net8

### ISSUE THREAD

**Issue by jdtcn** [gregsdennis/json-everything#532]
### Nuget Package

Json.More.Net

### Package Version

1.9.0

### Can this library make doing something simpler?

Hello!

Thanks for the cool library, that it is powered by System.Text.Json. Recently I tried to use this library in a net 8 application compiled in NativeAOT, and everything works if you do `JsonSchemaBuilder().FromType<T>().Build();`

Then I tried parsing the schema from the file as `JsonSchema.FromText(schema, options);` but this unfortunately doesn't work in NativeAOT, there are two problems:

* You need to create a custom converter for type `JsonConverter<Dictionary<string, JsonSchema>>` - that's pretty simple and after that the second problem occurs - 

* Method `Copy` In file `json-everything/Json.More/JsonNodeExtensions.cs:195` calls Deserialize without passing there `JsonSerializerOptions options` that are used to work in NativeAOT, and it fails `InvalidOperationException(JsonSerializerIsReflectionDisabled)`. This happens when calling `GetConstraint` from `ExamplesKeyword`.

It would be great if you could pass the JsonSerializerOptions options parameter in there, in this case your library will be able to parse schemas from string in NativeAOT mode.

Thanks!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gregsdennis** [comment]
Thanks for reporting this.  I'm not familiar with NativeAOT.  Would you be able to set up a reproduction with instructions to run it?

**Comment by gregsdennis** [comment]
I've reimplemented `.Copy()` to not use the serializer.  Please try _Json.More.Net_ v1.9.1.

**Comment by jdtcn** [comment]
Awesome, thanks for quick response! That helped, now Json.More.Net version 1.9.1 works with NativeAOT.

I've been experimenting further and found that there's another place that may be causing problems - `JsonSchema/ErrorMessages.cs:55`, there is a call to `JsonSerializer.Serialize` where a new instance of JsonSerializerOptions is created. But there is a workaround - add `<JsonSerializerIsReflectionEnabledByDefault>true</JsonSerializerIsReflectionEnabledByDefault>` in csproj, then everything will work.

But it would be cool to also inherit the JsonSerializerOptions in this place (NativeAOT needs TypeInfoResolver).

I created an example NativeAOT exe app, it will check the file against the schema, here it is - https://github.com/jdtcn/NativeAotJsonSchema

To run the example in NativeAOT mode, go to the project folder and run the dotnet publish command. The publish output will contain an exe file, you can just run it in the console.

In the example I added two converters that are needed for NativeAOT - *ListJsonSchemaConverter* and *DictionaryJsonSchemaConverter*, because you use *Read<List<JsonSchema>>* and *Read<Dictionary<string, JsonSchema>>*, also I had to add DefaultJsonTypeInfoResolver manually, because your converters are `internal` (so it's not easy to get them), if they were public then it might be possible to build a SourceGenerationContext that will not require DefaultJsonTypeInfoResolver. TrimmerRootDescriptor.xml is needed so that dotnet doesn't throw out some necessary types that are used via Reflection, I haven't figured out what exactly the trimmer throws out yet, but I'll look into it.

**Comment by gregsdennis** [comment]
> `JsonSchema/ErrorMessages.cs:55`, there is a call to `JsonSerializer.Serialize` where a new instance of `JsonSerializerOptions` is created.

Yes, I have to have that in order to embed the data of the error into the message.

> add `<JsonSerializerIsReflectionEnabledByDefault>true</JsonSerializerIsReflectionEnabledByDefault>` in csproj, then everything will work.

@eiriktsarpalis, I've read through https://github.com/dotnet/maui/issues/16038 regarding this property, but that seems to focus on application-level projects (e.g. MAUI).  What is the guidance around including this for a .Net Standard 2.0 project?

I also can't seem to find any docs for this property.

Thanks.

**Comment by eiriktsarpalis** [comment]
We're still in the process of writing up documentation for this, but TL;DR libraries cannot influence the value of feature switches set at the application layer. It should still be possible to read the value and react accordingly, using the v8 NuGet package it can be done using the `JsonSerializer.IsReflectionEnabledByDefault` property (which is also treated as a link-time constant in trimmed apps) or in earlier versions by manually reading the `System.Text.Json.JsonSerializer.IsReflectionEnabledByDefault` AppContext switch.

**Comment by jdtcn** [comment]
Sorry, that's just me being vague, I'm not suggesting adding `<JsonSerializerIsReflectionEnabledByDefault>true</JsonSerializerIsReflectionEnabledByDefault>` to your library, it needs to be added to a project that uses your library to make NativeAOT work. Just wanted to share ways to make it work.

Putting System.Text.Json.JsonSerializer.IsReflectionEnabledByDefault AppContext var in NativeAOT mode will not work, as it will be overridden, here is a discussion of how it works for NativeAOT - https://github.com/dotnet/runtime/issues/84378

**Comment by eiriktsarpalis** [comment]
@gregsdennis you might want to consider turning on the AOT compatibility analyzer for your library: 

https://learn.microsoft.com/en-us/dotnet/core/deploying/native-aot/?tabs=net8plus%2Cwindows#aot-compatibility-analyzers

**Comment by gregsdennis** [comment]
That would mean I'd have to target .net 8, right?  Currently, I'm only targeting .Net Standard 2.0.

**Comment by eiriktsarpalis** [comment]
I _think_ it should work so long as you're using the .NET 8 sdk.

**Comment by gregsdennis** [comment]
Just starting to look at this.  It seems that I have to multi-target with net8 in order to take advantage of the analyzer.  I suppose that makes sense since in order to have serializer contexts, I need net8 anyway.  That's a lot of divergent code.

I'm starting to wonder if I really need to support .Net Standard anymore.  I know that it's the only way to support .Net Framework, but as we're 8 versions outside of that now, I question the need to keep that support.  I'd really like to start taking advantage of features in later versions.

@eiriktsarpalis can you provide any insight?  From the MS support docs, it looks like Framework might be relevant for another 5 or 6 years.  I definitely don't think I can hold off that long.

**Comment by eiriktsarpalis** [comment]
Just because msft is supporting Framework, it doesn't mean that every library author should be expected to do the same. I would recommend doing what's best for you and your users.

**Comment by gregsdennis** [comment]
Now I just need to figure out how to get non-bug/enhancement feedback from library users.

**Comment by gregsdennis** [comment]
I'd like to support trimming/AOT to more of a degree than just marking everything as requires reflection, but I need to move to .Net 6 or 8 to really do it right, and it doesn't look like I'm going to be moving from .Net Standard any time soon.  (I'm informed that the project is pretty heavily used in some significant projects that can't or don't want to update.)  I'm still contemplating that.

**Comment by jevansaks** [comment]
I'm interested in leveraging JsonSchema.NET from an AOT app and am blocked by this issue. I cloned the repo and started looking into how to fix it. I _think_ that multi-targeting won't be that painful and you can keep netstandard2.0 support while still lighting up the AOT compatibility with small amounts of #ifdefs or polyfills. 

If you would be willing to accept the contribution @gregsdennis , I was going to start looking into this. My thinking would be to contribute as two parts:

1. Update projects to `<TargetFrameworks>netstandard2.0;net8</TargetFrameworks>` and add test coverage to test in both modes.
2. Enable the AOT compatibility checkers and fix the AOT blocking issues. 

Thoughts? I wanted to ask before I surprise anyone with a big PR.

**Comment by gregsdennis** [comment]
It's appreciate the support.

Be aware that the dependency packages, _More_ & _Pointer_, will also need to be updated since they do some incompatible things with reflection.

I also just had a fairly deep dive in #615 around a converter for tuple types.  I'm starting to think more that just moving on from .Net Standard (#390) might be the right course of action.

**Comment by jevansaks** [comment]
Yeah, I noticed some of those. We don't need to everything in the library AOT compatible, it's ok to tag the things that are hard to convert as `RequiresDynamicCode`.

I've sent out PR #618 to lay the groundwork so we can do NAOT things in a future change.

The main thing I'm looking to address is NAOT support in `JsonSchema.FromText`. I'm following [the docs](https://learn.microsoft.com/en-us/dotnet/standard/serialization/system-text-json/source-generation?pivots=dotnet-8-0) and adding a tagging all the things in the codebase that have JsonConverters into source generators.

One issue I stumbled on is that some of the tests (VocabularyTests) seem to expect to be able to register additional types to get parsed out. Is the total set of types that we need to deserialize into not statically knowable at compile time? Can callers extend the set of types?

If yes then maybe we need two versions of FromText, one that allows that and one that doesn't since I'm not sure how to mix & match the dynamically registered types from the source generator types.

**Comment by Sergio0694** [comment]
> "Why is this an issue? The types here are explicit."

That is not sufficient. Deserializing even strongly typed objects is not AOT-compatible by default.

> "What needs to be source generated? Anything that needs a converter already has one, and it's all custom code."

The JSON type info (ie. the JSON metadata). Eg. [see here](https://learn.microsoft.com/en-us/dotnet/standard/serialization/system-text-json/source-generation?pivots=dotnet-8-0).

> "It should be knowable at compile time."

Like mentioned above, that's not enough to make it AOT compatible with NativeAOT. It may just happen to work on eg. Mono LLVM or .NET Native just because they are more lenient and trim stuff less aggressively. NativeAOT is much more strict.

**Comment by jevansaks** [comment]
Thanks @Sergio0694 for helping explain this, I'm a new to Native AOT as well. The JsonConverters in JsonSchema are great, and they are still needed with NativeAOT. The solution System.Text.Json chose for solving this is by introducing these JsonTypeInfo things which are the static glue between the types and the JsonConverters for them.

>  Registering a new keyword uses a generic method, which means that an app that uses custom keywords will call that with types that aren't known here.

Thanks for clarifying that. I'll need to think about how to handle this, but I suspect we'll need to follow S.T.J's pattern and have JsonSerializationContext overloads so that we can have callers do the same JsonTypeInfo dance with their custom defined types.

**Comment by eiriktsarpalis** [comment]
> It seems that I have to multi-target with net8 in order to take advantage of the analyzer. I suppose that makes sense since in order to have serializer contexts, I need net8 anyway. That's a lot of divergent code.

At risk of stating the obvious, wouldn't setting the minimum STJ NuGet version to be 8.0.0 in the `netstandard2.0` target address some of those concerns without needing to multi-target?

**Comment by gregsdennis** [comment]
@Sergio0694 I'm trying to understand, but your answers are basically "that's just how it is."  I've read through that documentation several times over the past year.

My understanding of JSON type info is that it's compiler-generated reflection information.  But if there's a converter, there should be no need for reflection.  So why is JTI still needed?

Additionally NAOT aims to support non-JIT environments, which means that nothing that can't be determined at compile time is allowed, things like open generics.  But AOT really only applies when building something executable (i.e. an app), and I'm not really sure how that plays into building libraries.

**Comment by gregsdennis** [comment]
@eiriktsarpalis just switching over to STJ v8 on master, I see everything passes except for the new tuple converter tests as run in .Net Core 3.1, and it's really odd.  It seems doubles are serialized differently:

```
  Expected string length 23 but was 38. Strings differ at index 22.
  Expected: "[1,"string",false,-4.2]"
  But was:  "[1,"string",false,-4.2000000000000002]"
  ---------------------------------^
```

I can put a condition on the 3.1 target to use STJ 6, though.

**Comment by gregsdennis** [comment]
@eiriktsarpalis in your [blog post](https://devblogs.microsoft.com/dotnet/system-text-json-in-dotnet-8/#disabling-reflection-defaults), you mention that basic serialization like

```c#
JsonSerializer.Serialize(42);
```

requires disallowed reflection.  I think this is where my understanding is breaking.  Is that in the `options.GetConverter()` method?  I wouldn't expect more than a `.GetType()` is needed to find the appropriate JSON converter, cast it to the appropriate `JsonConverter<T>`, and call `.Write()`.  Where is the disallowed reflection?

My point in asking is to lead toward answering this question:  How do I know when I am using unsupported reflection?  There are a lot of places in these libs that use reflection, and it's seeming like there's going to need to be a lot of rewrite in order to support JTI and NAOT.

**Comment by Sergio0694** [comment]
> "How do I know when I am using unsupported reflection?"

Set `<IsAotCompatible>` in your project and then just fix all warnings until there's none 🙂
I recommend also checking out this blog post: https://devblogs.microsoft.com/dotnet/creating-aot-compatible-libraries/.

**Comment by eiriktsarpalis** [comment]
> I think this is where my understanding is breaking. Is that in the options.GetConverter() method? I wouldn't expect more than a .GetType() is needed to find the appropriate JSON converter, cast it to the appropriate JsonConverter<T>, and call .Write(). Where is the disallowed reflection?

The `JsonSerializerOptions` parameter in these methods is optional, so if that's missing it gets filled using the `JsonSerializerOptions.Default` value which is the one that uses unsupported reflection. Assuming you're passing it an options parameter from a `JsonSerializerContext` then it would work in AOT, albeit with a false positive warning about unsupported APIs being invoked.

**Comment by gregsdennis** [comment]
Okay.  I think the best way for me to gain this understanding is to just work through doing this myself.  I believe that other people can make these updates, but I really need to be sure I understand my own code base.

I've started a `native-aot` branch with a few other changes I want to include in the next versions.  I welcome anyone who wants to contribute directly to create PRs against that branch.

**Comment by jevansaks** [comment]
@gregsdennis I am still working through the NAOT changes in my fork. I'll share the changes later today so you can see the gist of what I've done. I'd also be happy to get on a chat or a call to explain my understanding of things. I totally understand wanting to work through it yourself, that's partly why I'm hacking on this too. :)

**Comment by gregsdennis** [comment]
Join me in Slack if you'd like to chat in a more "live" way (whether just more realtime or on a call).  There's a link in the readme.
