### ISSUE TITLE
Am I using Format correctly?

### ISSUE THREAD

**Issue by martinp999** [gregsdennis/json-everything#54]
I have a schema that was partly described as -

``` 
schema = new JsonSchemaBuilder()
                .Schema("https://json-schema.org/draft/2019-09/schema")
                .Id("http://acme.com/components/purchaseorder")
                .Type(SchemaValueType.Object)
                .Properties(
                   ...,
                    (
                        "DateRequested", new JsonSchemaBuilder()
                            .Format(new Format("date-time"))
                    ),...
```

and validated as -

```
ValidationOptions options = new ValidationOptions();
options.ValidateAs = Draft.Draft201909;
options.OutputFormat = OutputFormat.Detailed;
options.ValidateMetaSchema = true;

var res = schema.Validate(sbMessageBodyJson, options);
```
The above returns TRUE;

What I have since realised is that `DateRequested=="1/1/0001 12:00:00 AM"`, the datetime formats provided by way of `new Format("date-time")` are as defined in [Formats.cs](https://github.com/gregsdennis/json-everything/blob/master/JsonSchema/Formats.cs) and the latter should not match the former.  The validation should have returned FALSE;

It has been mentioned [in the documentation](https://gregsdennis.github.io/json-everything/usage/schema/validation.html) that (paraphrasing) "Format should be an annotation that _can_ provide validation so long as that validation may be configured on and off", and I am aware of [this now closed issue](https://github.com/gregsdennis/json-everything/issues/33), but I am confused as to what it all means.

Can I validate using a Format and, if so, am I doing it correctly?

**Comment by gregsdennis** [comment]
To get format validation you will need to enable the `RequireFormatValidation` option (`ValidateFormat` if using a version prior to v1.6.0).  This will _force_ `format` to validate rather than just producing an annotation.

(I need to update that documentation as things have change a bit with v1.6.0.)

**Comment by martinp999** [comment]
Wow!  Now that is what I call a quick response!  Thank you.

I am using v1.5.2; should I upgrade and would there be any refactoring (besides that you have mentioned above)?

**Comment by gregsdennis** [comment]
Also, instead of using `new Format("date-time")`, you want to use `Formats.DateTime`.  The spec-defined formats have been provided.  Creating a new `Format` instance doesn't provide any validation.  There are a couple derived classes that override the `Validate()` method that are used for the in-built ones.

Lastly, the `ValidateAs` option is provided in case the schema doesn't have a `$schema` keyword.  This keyword will _always_ be respected, even when the option is set to something else.  Since your schema has this keyword, you don't need to set the option.

**Comment by martinp999** [comment]
Many thanks for the answers and, once again, many thanks for the library.
