### ISSUE TITLE
Is it possible to make custom JSON converters public to support source generation?

### ISSUE THREAD

**Issue by shenglol** [gregsdennis/json-everything#549]
### Describe the functionality that isn't covered by this suite.

I would like to utilize source generation in `System.Text.Json` for some POCOs that rely on types from this package, such as `JsonPointer`. However, it appears that the source generator consistently includes the custom JsonPointerJsonConverter, which is `internal` and is applied to the `JsonPointer` class, leading to a build failure.

The issue can be reproduced with the following code:

```C#
// Build error: 'JsonPointerJsonConverter' is inaccessible due to its protection level
public record ErrorResponse(string Code, string Message, JsonPointer? Target);

[JsonSerializable(typeof(ErrorResponse))]
public partial class ErrorResponseContext : JsonSerializerContext { }
```

### Describe alternatives you've considered.

Would it be possible for you to consider changing the visibility of the custom JSON converters to `public`?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gregsdennis** [comment]
Hey there.  Sorry for not getting to this sooner.

I don't know a lot about the interaction between JSON source gen and the standard converters.  My understanding was that they were different systems, but it seems the source gen uses converters if they're defined.

I don't see a problem with exposing them.  I didn't originally because it wasn't necessary.
