### ISSUE TITLE
Transforming Rule to Expression Tree for LINQ?

### ISSUE THREAD

**Issue by cdroulers** [gregsdennis/json-everything#552]
### Nuget Package

JsonLogic

### Package Version

latest

### How can I help?  Please provide as much context as possible.

Hello!

I'm trying to find an easy, portable way to represent user-entered filter parameters to a database. The filters will be fairly simple, but I always like to find something a little standardised to avoid re-inventing the wheel. I've looked at many custom JSON schemas, CEL, SpEL, etc.

After finding https://react-querybuilder.js.org/ for the eventual UI (won't be using it right away), I discovered JSON logic and this library.

I'm currently trying to figure out if there's an existing way to transform JSON logic to a .NET Expression tree that can be passed to EFCore, ideally with possibilty for constants to parameterized, but that can be fixed later.

I see that all properties are internal to avoid mutability, but having them exposed publicly (through immutable collections) could allow me to visit each node and transform to expression tree.

Or maybe there is already a visitor pattern that can be applied, but I couldn't really figure that out from the very little docs I could find! Everything being internal prevents navigating the tree of rules (as mentioned in this issue https://github.com/gregsdennis/json-everything/issues/154)

I'm not fully set on using JsonLogic, but I'm throwing the question out here in case there's a way I'm missing or some other way that could make sense! 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gregsdennis** [comment]
I currently don't have such functionality, no.  That kind of translation will take some planning.  If you have some ideas, I'd be happy to hear them.

**Comment by cdroulers** [comment]
Hi Greg! Thanks for the answer!

We're looking to store some filter logic in our database in a way that's easy to understand for humans and machines alike. We use the filter to query our DB and set some permissions according to query results.

I've written a small POC over the weekend using SQL

```csharp
where = GetWhere("Name = 'TEST' OR Id IN (1, 2)");
var exp = GetWhereExpressionLambda<TestData>(where.SearchCondition);
```
Walking the SQL structure (using `Microsoft.SqlServer.TransactSql.ScriptDom`) I can generate an Expression tree (using Expression.Lambda and other methods)

```
// {x => ((x.Name == "TEST") Or value(System.Collections.Generic.List`1[System.Int32]).Contains(x.Id))}
.Lambda #Lambda1<System.Func`2[ProjectName.UnitTest1+TestData,System.Boolean]>(ProjectName.UnitTest1+TestData $x)
{
    $x.Name == "TEST" | .Call .Constant<System.Collections.Generic.List`1[System.Int32]>(System.Collections.Generic.List`1[System.Int32]).Contains($x.Id)
}
```

I was thinking that an equivalent JSON logic could be walked to build an expression tree

```json
{
  "and": [
    { "==": [{ "var": "Name" }, "TEST"] },
    { "in": [{ "var": "Id" }, [1, 2]] }
  ]
}
```

Since JSON logic syntax is supported by multiple React query builders, I thought it'd be a good candidate for parameter storage.

I'm probably going with SQL syntax for our current project, but it's always fun to play around with something like this.

I originally didn't fully realize how JsonLogic was meant to be used, but when I look around for querying languages, there's many options, and they all come back to something like this!

Either exposing the properties (in read-only, immutable way) would allow for recursive code, or exposing a visitor pattern like the existing `Apply`, but for return an `Expression` instead of a `JsonNode`!

I hope this makes sense and thanks for answering!

**Comment by gregsdennis** [comment]
I wonder if JSON Logic is the right tool for what you're trying to do.  It seems like you want more of a querying tool, like JSON Path.

If I were to rewrite that Logic with a Path, it'd be:

```jsonpath
$[?@.Name == 'TEST' && @.Id in [1,2]]
```

I think this aligns with your SQL a bit better as well.

Now, that does have a few gotchas:

- While this is likely to be [supported in many implementations](https://cburgmer.github.io/json-path-comparison/), it's not spec-compliant:
  - JSON constructs (arrays and objects) are not permitted in the filter syntax; only primitives are allowed.
  - The `in` operator isn't defined by the spec.
- In order to make _JsonPath.Net_ do this, you'll need to enable some options on `PathParsingOptions`.

But you _can_ test this on https://json-everything.net/json-path.

**Comment by cdroulers** [comment]
Thanks for the input, JSON Path does look like a possibility. I will look into it!

**Comment by gregsdennis** [comment]
There's still the open question of whether I can convert a path into a Linq expression.  I'll have to look into it.  It's going to take time, though.  Happy for suggestions/PRs.

**Comment by cdroulers** [comment]
I'll try to check it out soon, but I think parsing SQL is the simplest
solution for now!

**Comment by cdroulers** [comment]
@gregsdennis Just created a PR for a POC!

**Comment by gregsdennis** [comment]
Closing for now, but I've marked this to revisit.

**Comment by jack775544** [comment]
I have been slowly working away at doing this on a fork of the repo [here](https://github.com/jack775544/json-everything/tree/logic-expressions).

The code quality isn't great right now but things are mostly working with some caveats

* Some .NET methods do not match nicely to their JSON logic equivalents
  * For example, the C# and JSON logic substring methods are fairly different from each other.
  * I chose to keep the C# behaviour in this case to keep max compatibility with tool like EF.
* Support for objects as inputs is not possible without a lot of work. This is since doing this with idiomatic code requires using concrete classes (either named or anonymous). Since an input object can have any shape, this would require runtime class generation, which is a bit of a rabbit hole.
* There is a considerable amount of reflection that is needed which analysers in the repo complain about.
  * Need to call things like `MakeGenericType` which break AOT.
  * Since expressions are most likely going to be used other non-AOT compatible libraries, I don't see this as a big concern.

Though the biggest pain point (and currently the biggest cause of bad code in my fork!)

Type differences
  * All logic inputs are going to come in as one of the JSON primitive types (ie. undefined, null, string, number or bool) via literal rules.
  * There is not a 1 to 1 mapping of logic input type to JSON primitive type
  * Take the following example:

  ```cs
  public class TestData
  {
    public int IntField { get; set; }
    public double DoubleField { get; set; }
    public string StringField { get; set; }
    public DateTime DateField { get; set; }
  }
  ```

  and the following JSON Logic

  ```json
  { 
    "and": [
      { "==": [{ "var" : ["IntField"] }, 1] },
      { "==": [{ "var" : ["DoubleField"] }, 1] },
      { "==": [{ "var" : ["StringField"] }, "testing"] },
      {
        "or": [
          { "==": [{ "var" : ["DateField"] }, "2020-01-01T00:00:00"] },
          { "==": [{ "var" : ["DateField"] }, "2020-01-01T00:00:00Z"] },
          { "<": [{ "var" : ["DateField"] }, "2020-01-01T00:00:00"] }
        ]
      }
    ]
  }
  ```

  You can see in the first equals expression, `1` will need to be typed as an int where in the second one it will need to be a double. Similarly in the third equals expression the literal will need to be a string, where in the other expressions in the or rule the string will need to be converted to a `DateTime`. This problem is larger when you realise that .NET has a lot of different number types (16, 32, 64 bit integer and floating point types, as well as byte and decimal).

  This also raises some interesting issues with strict vs loose equality. Since if we try to compare 2 different types we get an exception, we basically always need to perform conversions. Since only allowing a subset of conversions in strict equals was something I wanted to do, the strict equals implementation is now the same as loose equals.

### What next?

* Code cleanup
* Fixing tests
  * I duplicated the existing test suite for the logic rules and made them use expressions instead.
  * Due to the behaviour differences mentioned above, this is causing some of the existing test cases to fail.
* I want to move the expressions code into its own project and not just embedded into the main logic project.
  * Due to the fields on the rules being marked as `internal`, an `InternalsVisibleTo` assembly attribute would need to be added to the main logic project.

I would be happy to any feedback on this.

**Comment by gregsdennis** [comment]
Wow, that's a lot!

I've actually been reconsidering some of the implementation decisions in this library, and I think I'd like to try to re-implement it using the more functional approach I used for JSON-e.  There's some details about the context that I'd like to borrow from that as well.

**Comment by jack775544** [comment]
That makes sense to me. I have updated my fork to separate the expression logic out into a separate project. I'll do some more code cleanup and then merge these new changes in. Very nice performance improvements with that change.

**Comment by toddsmith-adsk** [comment]
@jack775544  For the EfCoreTests these types of tests will fail:

```
		var array = new JsonArray("1", "3");
		var rule = new InRule(new VariableRule("Id"), array);
		var expression = RuleExpressionRegistry.Current.CreateRuleExpression<Department, bool>(rule, _options);
```

```
		var array = new JsonArray("Management", "HR");
		var rule = new InRule(new VariableRule("Name"), array);
		var expression = RuleExpressionRegistry.Current.CreateRuleExpression<Department, bool>(rule, _options);
```

```
		var array = new JsonArray("Jane", "John");
		var rule = new SomeRule(new VariableRule("Employees"), new InRule(new VariableRule("Name"), array));
		var expression = RuleExpressionRegistry.Current.CreateRuleExpression<Department, bool>(rule, _options);
```

```
System.InvalidOperationException : The LINQ expression 'DbSet<Department>()
    .Where(d => string.Join(
        separator: __Field_0, 
        values: [__Field_1,__Field_2]
            .Select(e => e.ToString())).Contains(d.Id.ToString()))' could not be translated. 
```

**Comment by toddsmith-adsk** [comment]
@jack775544 if I end up trying to call RuleExpressionRegistry.Current.CreateRuleExpression in my app I get access method exceptions due to the internal declarations.

**Comment by jack775544** [comment]
@toddsmith-adsk Thanks for testing my version out. I have updated my fork to better support array literals as well as fix the In rule so those cases actually work now. There are a lot of edge cases that can up with building in expressions so finding these sorts of issues is very helpful.

As for using it in another application, you are probably not calling the intended public API. Usage should look something like this:

```cs
var rule = JsonSerializer.Deserialize<Rule>("...");
var expression = RuleExpressionRegistry.Current.CreateRuleExpression<SomeClass, bool>(rule);
```

This is similar to how the normal JsonLogic code in this repo gets called.
