### ISSUE TITLE
Is there any way to find single value with recursive descent rather than checking entire subtree?

### ISSUE THREAD

**Issue by qt-kaneko** [gregsdennis/json-everything#583]
### Documentation

- [X] I have consulted the [documentation](https://docs.json-everything.net), and my question isn't answered there.

### Nuget Package

JsonPath.Net

### Package Version

0.6.7

### How can I help?  Please provide as much context as possible.

I'm trying to parse InnerTube API and it is painfully slow when running in browser. Average response is from 30k to 60k lines. Absolute path working a lot better.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gregsdennis** [comment]
Hey there. 

- Do you have a link or other reference?
- What are you trying to do?
- What have you tried?
- How is what you've tried not doing what you want?

**Comment by qt-kaneko** [comment]
I'm trying to parse response JSON from InnerTube API (there are no links because InnerTube is private API) into more usable form, full path to property I need looks like `$.contents.twoColumnBrowseResultsRenderer.tabs[0].tabRenderer.content.richGridRenderer`, so I'd like to write it just like `$..richGridRenderer`, but it is very slow when running in browser (Blazor), as I think, due to it checks all of subtree, but I need only single value.

**Comment by gregsdennis** [comment]
What you're looking for can't be done with JSON Path.  `$..richGridRenderer` inherently finds _all_ `richGridRenderer` properties _everywhere_ within the data.  There's not anything in JSON Path that will just give you the first one in the result set.

That said, although the query is built as a deferred-execution Linq query, `NodeList` does evaluate the results and store them in a list.  I could look into _not_ evaluating the result, which would let you do something like:

```c#
var path = JsonPath.Parse("$..richGridRenderer");
var results = path.Evaluate(data);
var first = results.First();
```

Then you would only be bound by Linq's ability to evaluate.

This would be a breaking change, however, since

- `NodeList` currently implements `IReadOnlyList<Node>`, which would need to change to `IEnumerable<Node>`
- `NodeList` current represents an evaluated query, which would change to a deferred-execution query

**Comment by gregsdennis** [comment]
This wasn't too hard, and I really like the functionality that it enables by appending further linq queries.

In the end, the code will look like this:

```c#
var path = JsonPath.Parse("$..richGridRenderer");
var results = path.Evaluate(data);
var first = results.Matches.First();
```
