### ISSUE TITLE
Accept Decimal for Number

### ISSUE THREAD

**Issue by coolhome** [gregsdennis/json-everything#63]
**Describe the bug**
Unable to use decimal with all number based validators, like `ExclusiveMaximumAttribute`.

**To Reproduce**
```cs
public class SomeEntity
{
    [ExclusiveMaximum(75.00m)]
    public decimal Percentage { get; set; }
}
```

**Expected behavior**
I believe the specification in draft-8/2019‑09 says any number

**Comment by gregsdennis** [comment]
Thanks for the report. I actually use decimal as the default numeric type within the libraries, so I'm curious as to what's going on.

Could you let me know which library and version this is, please?

**Comment by coolhome** [comment]
I think its just an oversight but have not had too much time to take a deep dive yet. I believe its the fact the attributes only accept a `uint` and not a decimal, double, or float.

https://github.com/gregsdennis/json-everything/blob/0e941ed08f671cef0689027f44ef7430f28d9a70/JsonSchema.Generation/ExclusiveMaximumAttribute.cs#L22

**Comment by gregsdennis** [comment]
> Could you let me know which library and version this is, please?

Okay... so I'm guessing you're looking at the Schema.Net.Generation library.

The reason decimal isn't included is because [C# doesn't support decimals as attribute arguments](https://github.com/dotnet/csharplang/blob/master/spec/attributes.md#attribute-parameter-types).  The system will still generate the appropriate schema.
