### ISSUE TITLE
Generate Data generate data that is not valid additionnalProperties ; false  management

### ISSUE THREAD

**Issue by LasneF** [gregsdennis/json-everything#647]
### Nuget Package

JsonSchema.Net.Data

### Package Version

online 

### Operating System

None

### .Net Target (if relevant, please specify the version in the description)

None

### A clear and concise description of the bug.

given a schema , the data generated by the tool does not pass data validation (same schema same data) 

i suspect the usage of additionnalProperties set to false not properly handled 

### What did you expect?

similar behavior on data generation  / data validation 

### Please add test code or steps to reproduce the behavior.

```
{
"$schema": "http://json-schema.org/draft-07/schema#",
"type": "object",
"additionalProperties": false,
"oneOf": [{
  "required": ["A"],
  "properties": {
   "A": {"type": "string"},
   }
},
{
   "required": ["B"],
   "properties": {
     "B": {"type": "string"}
    }
    
  }
]
}
```

case where it generate data even if the additionnal properties is set to false 
same if i put in addtionnal properties in the section of the oneOf , or in both section (top and oneOf)
![image](https://github.com/gregsdennis/json-everything/assets/12461661/3419304c-590b-4ac7-a984-811375cc66c2)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gregsdennis** [comment]
Actually, the problem here is how `additionalProperties` works.  It can't "see into" the `oneOf`, so it doesn't know that the properties `A` and `B` have been defined.

If you try to generate data for 

```json
{
  "type": "object",
  "additionalProperties": false
}
```

you'll find that it only ever generates empty objects.

That means that the schema you provided actually has no valid instances.

- The `additionalProperties` says that there aren't any properties defined, and that there can be no more.
- The `oneOf` says that there either needs to be an `A` property or a `B` property.

Since both of these can't be true, there are no valid JSON instances.

When you give the system a schema like this, it makes an attempt to detect that it can't create valid data, but sometimes it just cries and gives you something anyway.

---

FWIW, I also tried this with `unevaluatedProperties`, which _can_ see into the `oneOf`, but the problem persists.

**Comment by LasneF** [comment]
is there a priority order defined  like additionnalProperties > oneOf ? 
the statement looks weird , or at least counter intuitive 

you mean that 

{
"$schema": "http://json-schema.org/draft-07/schema#",
"type": "object",
"additionalProperties": false,
"oneOf": [{
  "required": ["A"],
  "properties": {
   "A": {"type": "string"},
   }
}] 
}

is not equivalent to  

{
"$schema": "http://json-schema.org/draft-07/schema#",
"type": "object",
"additionalProperties": false,
"required": ["A"],
  "properties": {
   "A": {"type": "string"},
   }
}

semantically it looks the same to me

**Comment by gregsdennis** [comment]
Those two schemas are indeed not equivalent, yes.

The `additionalProperties` keyword depends on `properties` and `patternProperties`, but those keywords MUST be adjacent keywords.  That is, they MUST appear in the same JSON object at the same level.  It can't "see into" the `oneOf` and find the `properties` in there.

That's why we added `unevaluatedProperties`.  It _does_ have the ability to "see into" the `oneOf` (and other keywords).  It depends on `properties`, `patternProperties`, `additionalProperties`, and even other `unevaluatedProperties` that are adjacent or contained in subschemas of adjacent keywords.

> is there a priority order defined like additionnalProperties > oneOf ?

No, it only depends on those two keywords mentioned above.

**Comment by LasneF** [comment]
thanks for the presicion @gregsdennis, it not obvious ,  it can be a good subkect to write on article on it !
