### ISSUE TITLE
Polish language localization

### ISSUE THREAD

**Issue by r-duzy** [gregsdennis/json-everything#663]
### Documentation

- [X] I have consulted the [documentation](https://docs.json-everything.net), and my question isn't answered there.

### Nuget Package

JsonSchema.Net (language pack)

### Package Version

6.0.3

### How can I help?  Please provide as much context as possible.

Hello, we need polish language localization for schema validation errors. Would you be able to implement this? Of course I can provide file with translations.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gregsdennis** [comment]
Yes, this can be done. Please submit a PR like #657, which adds the Russian translation, and I can publish a package for it.

**Comment by gregsdennis** [comment]
@r-duzy is this something you'd be interested in handling?

**Comment by r-duzy** [comment]
Thank you, sorry it took so long. I tried to push these changes but I get 403 error. Here are the translations.
[Resources.pl-PL.resx.zip](https://github.com/gregsdennis/json-everything/files/14458068/Resources.pl-PL.resx.zip)

**Comment by gregsdennis** [comment]
@r-duzy you're getting a 403 because you're trying to push to this repository.  You'd need to [create a fork](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/fork-a-repo) of this repo under your username, make the changes there, and then [create a PR](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork) back to here.  This is the basic Github workflow for contributing to a project you don't own.

I'll go ahead and incorporate your resx file.  Thanks for that.

**Comment by r-duzy** [comment]
I see. Thanks for your help, we can close this issue then.

**Comment by gregsdennis** [comment]
I'm taking care of this, but the issue needs to remain open until it is resolved.
