### ISSUE TITLE
Deconstruct JsonLogic for conversion into another format

### ISSUE THREAD

**Issue by birgerj** [gregsdennis/json-everything#668]
### Documentation

- [X] I have consulted the [documentation](https://docs.json-everything.net), and my question isn't answered there.

### Nuget Package

JsonLogic

### Package Version

5.0

### How can I help?  Please provide as much context as possible.

I have an app that internally uses JsonLogic to describe some rules for objects. 
Nog I need to convert the JsonLogic rules into another format. I was hoping to do that by deserializing the JsonLogic string and then checking the rule:
```cs
var rule = JsonSerializer.Deserialize<Json.Logic.Rule>(jsonLogicString);
if (rule is AndRule andRule)
{
  foreach (var item in andRule.Items)
  // do stuff with items
}
else if (rule is OrRule orRule)
{
  // do stuff with orRule.Items
}
```
However, the `Items` properties (and other interesting properties) are all protected internal. 
Could these properties be made public so that the rules can be deconstructed again?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gregsdennis** [comment]
Hey there.  I think deserializing in the JsonLogic model might be overkill for your need.  Have you considered just parsing into JsonNode and browsing the JSON data that way?

```c#
var rule = JsonNode.Parse(jsonLogicString).AsObject();
if (rule.ContainsKey("and"))
{
  foreach (var item in rule)
  // do stuff with items
}
else if (rule.ContainsKey("or"))
{
  // do stuff with orRule.Items
}
```

You may also want to have a read through #368 as that's the issue where the `protected internal` entered the picture.

I _could_ make the properties public, but they're supposed to be immutible, so I'd have to change the property types as well.  Since they're accessible via subclasses, it'll be a breaking change.

**Comment by gregsdennis** [comment]
I just realized you could do this as well because the .Net team made ["decisions"](https://blog.json-everything.net/posts/jsonnode-odd-api/) with the `JsonNode` API:

```c#
var rule = JsonNode.Parse(jsonLogicString);
if (rule["and"] is not null)
{
  foreach (var item in rule["and"].AsArray())
  // do stuff with items
}
else if (rule.ContainsKey("or"))
{
  // do stuff with orRule.Items
}
```

**Comment by BirgerPosti** [comment]
I did go that way, but I was hoping that instead of string checking I could check types. That should be more accurate and allow for stricter typed code. But I followed your suggestion and that also works.
What you could do instead of exposing the `Item` property is exposing it as an enumerator. That seems to be what the .net team did for JsonDocument as well I think.
But no hurry, I have a working solution now. Thanks for looking into it.

**Comment by birgerj** [comment]
I did go that way, but I was hoping that instead of string checking I could check types. That should be more accurate and allow for stricter typed code. But I followed your suggestion and that also works.
What you maybe could do instead of exposing the `Item` property is exposing it as an enumerator. That seems to be what the .net team did for JsonDocument as well.

**Comment by gregsdennis** [comment]
Thanks for the recommendation.  I'll continue to play around with things to see what I can come up with.  Maybe extension methods would do?

**Comment by gregsdennis** [comment]
I think this could work:

```c#
public static IEnumerable<Rule> Items(this AndRule rule)
{
    return rule.Items.AsReadOnly();
}
```

**Comment by gregsdennis** [comment]
@birgerj would something like ☝️ work for you?  I can push this out soon.

**Comment by birgerj** [comment]
@gregsdennis yes, I could really use that! I already found a solution to my problem but this would allow me to make the code a lot more readable!

**Comment by birgerj** [comment]
@gregsdennis  thanks for your quick response and changes!
