### ISSUE TITLE
Dynamically modify the childrens properties of JsonSchema

### ISSUE THREAD

**Issue by thomashinsinger** [gregsdennis/json-everything#96]
I am currently using your library which work perfectly.

But I have some issues with dynamically modify the childrens properties.

Let me explain, I have two solutions that work, but I can't do everything I want.

1) The first one : 

I use this to generate the skeleton of an object : 

`JsonSchemaBuilder jschemaParent = new JsonSchemaBuilder().FromType<TEntity>();`

This is exactly what I want and work perfectly.

After that I want to be able to modify the childrens properties, and for that the only solution that I found is something like that : 

	IJsonSchemaKeyword proprietes = ((Json.Schema.JsonSchema)jschemaParent).Keywords.First(c => c is PropertiesKeyword);

	Dictionary<string, Json.Schema.JsonSchema> props = new Dictionary<string, Json.Schema.JsonSchema>();

	foreach (var property in ((PropertiesKeyword)proprietes).Properties)
	{
		JsonSchemaBuilder jsonBuilder = new JsonSchemaBuilder();

		foreach (IJsonSchemaKeyword keyword in property.Value.Keywords)
			jsonBuilder.Add(keyword);

		if (property.Key == "Numero")
			jsonBuilder.ReadOnly(true);

		props.Add(property.Key, jsonBuilder);
	}

	jschemaParent.Properties(props);

It works but I have to reimplement each property one by one, by getting each IJsonSchemaKeyword and then adding what I need.

Am I missing something, would there be no way to get a JsonSchemaBuilder from a JsonSchema to do it more easily ?

2) The second one : 

As the first solution I generate the skeleton of an object : 

`var context = SchemaGenerationContextCache.Get(typeof(TEntity), null);`

This also works perfectly. I then created custom Intents to modify children properties :

	PropertiesIntent properties = (PropertiesIntent)context.Intents.First(c => c is PropertiesIntent);

	foreach (var propriete in properties.Properties)
	{
		if (propriete.Key == "Numero")
			propriete.Value.Intents.Add(new ReadOnlyIntent(true));
	}

The problem with this solution is that if the object contains the same type of property several times, it will add the ISchemaKeywordIntent on each property.
For this example, if my object contains two strings, the code above will add two readonly on each strings, but I only want to have it on the property 'Numero' and not the other one.
What am I doing wrong with this solution, how I could avoid duplications of ISchemaKeywordIntent for each property of the same type ?

For any solution I want to generate the skeleton of an object, and then modify children properties, because I have some complex objects, and then modify children properties.

Am I missing something, would there be a simpler solution to do that ?

Thanks in advance and sorry if my english is bad !

**Comment by gregsdennis** [comment]
Your English is quite good.  Don't worry.

I think what you're going to need to do is create a `ReadOnly` attribute, following [these instructions](https://gregsdennis.github.io/json-everything/usage/schema-generation.html#attributes).

Then you just need to apply the attribute to the properties for which you want to add the `readOnly` keyword.

Rightfully, that and a corresponding one for `writeOnly` should be included in the library.  Looks like I missed those.  If you want to give a PR a go, I'd be happy to pull it in.  Otherwise I can create them.

**Comment by thomashinsinger** [comment]
I know I can achieve this with an Attribute, but for my needs I don't want do this with an Attribute.

To explain quickly, I have another objects which contains the configuration of my objects, and I want and have to use this object to improve dynamically my JsonSchema afterwords. 

The readonly example was the simpliest example to show my problem.

I have to add dynamically on my children properties !

**Comment by gregsdennis** [comment]
I think the best option requires a code change.

If I add in generation visitors that run just before the optimization step, the client (you) would be able to implement custom logic as a sort of "final review."  A visitor would be able to inspect what was generated and make modifications.

This combined with the `readOnly` intent should get you what you want.

But as I said, it requires an addition to the library and will take a little bit.

**Comment by thomashinsinger** [comment]
Thank you for taking the time to understand and answer my questions !

I will try on my side to find solutions to do what I need, if i find anything interesting i will keep you posted !

**Comment by gregsdennis** [comment]
Also, please note the disclaimer on the [docs site](https://gregsdennis.github.io/json-everything/usage/schema-generation.html):

> Ideally, this functionality should be used to create a starting point in authoring a schema. The schemas output by this library should be reviewed by actual people prior to being put into a production system.

I make no claim regarding the completeness of generated schemas.  They're accurate for what they provide, but they're also quite basic.

**Comment by genapi-bv** [comment]
Hello,
I'm a @thomashinsinger colleague.

First of all, thank you for being so reactive.
We've tried to achieve what we need based on your solution. By implementing an ISchemaRefiner we now have a clean way to dynamically modify the SchemaGeneratorContext, which is really great.

But we still have the same issue when we generate the schema.

The thing is that we dynamically add intents based on the name of properties. But with the current way of handling cache and optimisations (I mean implementations of SchemaGenerationContextCache.Get and SchemaGeneratorContext.Optimize), two contexts having the same Type and Attributes are always considered to be the same, even if their Intents are different.

So if we add an intent on a specific property of the string type for example, all string properties will have this intent.

I've found a way to achieve what we need by:
1. adding an "IsCacheable" property on SchemaGeneratorConfiguration and not caching contexts if the value is false.
2. adapting SchemaGeneratorContext.GetHashCode to take intents into account.

Now we can have properties of the same type but with different intents, which is currently possible only by using attributes.

Is this something that seems satisfying to you?

**Comment by gregsdennis** [comment]
I need to go back and look at the initial design and work refiners in better.  I definitely think it's the right approach, but it needs... refinement.

I had designed the cache to track each type/attribute set because that's what the generator encounters.  E.g.

```c#
class Foo
{
    public int Value { get; set; }

    [Maximum(5)]
    public int Other { get; set; }

    [Maximum(5)]
    public int OtherAgain { get; set; }
}
```

This would align `Other` and `OtherAgain` because they're defined the same and would have the same schema to represent them; thus they use the same context.  The optimization then merely find the contexts with more than one reference and creates a definition entry and a `$ref` for them.

But now that refiners have entered the picture, if you wanted to modify `OtherAgain` but leave `Other` as is, they would no longer be in alignment, and they need different contexts to indicate that.

I also think you're on the right track about using intents instead of attributes for equality comparison, but I need to dig in there a bit more.

I'll need to add in a mechanism that allows the refiners to do all of this.  Can you open a new ticket for this, please?
