### ISSUE TITLE
Modifying individual properties with Refiners

### ISSUE THREAD

**Issue by genapi-bv** [gregsdennis/json-everything#99]
Hello,

as requested this ticket is a follow up-to #96.

**Environment**
- Nuget Package: JsonSchema.Net.Generation
- Nuget Version: 1.3.0
- OS: Windows
- .Net Target: Core 5.x

**Can this library make doing something simpler?**
With the introduction of Refiners, we now have a clean way to dynamically modify the SchemaGeneratorContext.
But with the current design of the cache and optimization phase, we can't modify "individual properties".

**Describe alternatives you've considered**
Replace tracking of type/attribute set with tracking of type/intent set.

**Additional context**

Let's consider this class:

```
public class MyClass
{
    public string Name { get; set; }
    public string Description { get; set; }
}
```

and the associated refiner, which adds an intent to the Name property:

```
public class MyClassRefiner : ISchemaRefiner
{
    private static Dictionary<string, List<ISchemaKeywordIntent>> customIntents = new()
    {
        { "Name", new() { new MaxLengthIntent(42) } }
    };

    public void Run(SchemaGeneratorContext context)
    {
        foreach (var property in context.Intents.Where(i => i is PropertiesIntent).SelectMany(i => (i as PropertiesIntent).Properties))
        {
            if(customIntents.TryGetValue(property.Key, out var propertyCustomIntents))
            {
                foreach (var customIntentToAdd in propertyCustomIntents)
                {
                    property.Value.Intents.Add(customIntentToAdd);
                }
            }
        }
    }

    public bool ShouldRun(SchemaGeneratorContext context)
    {
        return context.Type.Equals(typeof(MyClass));
    }
}
```

Now let's build and serialize the schema for our type :
```
var schema = new JsonSchemaBuilder().FromType<MyClass>(new ()
{
    Refiners = new(){ new MyClassRefiner() }
}).Build();

Console.WriteLine(JsonSerializer.Serialize(schema, new JsonSerializerOptions { WriteIndented = true }));

```

We can see in the generated schema that both string properties have been considered equal, hence have been "grouped" by the optimizer :
```
{
  "type": "object",
  "properties": {
    "Description": {
      "$ref": "#/$defs/string"
    },
    "Name": {
      "$ref": "#/$defs/string"
    }
  },
  "$defs": {
    "string": {
      "type": "string",
      "maxLength": 42
    }
  }
}
```

What we expect is having only the Name property impacted by the added intent, like so:
```
{
  "type": "object",
  "properties": {
    "Description": {
      "type": "string"
    },
    "Name": {
      "type": "string",
      "maxLength": 42
    }
  }
}
```

**Comment by gregsdennis** [comment]
I'm having trouble with this.  The problem you're experiencing is that both properties use the same context.  This is because the generators sees them as needed the same subschema.  When you want to change one property you change the context.  But that context represents the other property as well.  What you'd need to do is create a new context object to represent your modifications.

To that end, I'd like to change the return type to the `Run()` method from `void` to `SchemaGenerationContext`.  With this you'll have two options:

1. Modify the context argument, thereby altering all references to that subschema (current behavior), and return null.
2. Create a new context to have your changes, and returning it, which will leave the other intact (what you're wanting).

The problem I'm having is coming up with a good way to let you create a new context.  I'm fine with a copy constructor, but the content needs to be copied, too.  The hard part about that is the intents, specifically the ones that implement `IContextContainer`, which hold other intents (e.g. `properties`).

The only solution I've been able to think of is to add a `Copy()` method to the `IContextContainer`, but that shifts the responsibility of getting the deep copy right to the client (because you can implement intents also), which I don't like.

I'm still looking at it.

**Comment by genapi-bv** [comment]
Another solution I can think of would be to let clients have a way to override the caching mecanism.
For example by implementing an ISchemaGenerationContextCache interface.

With this approach it would be possible to avoid contexts sharing.

**Comment by gregsdennis** [comment]
@genapi-bv, I'm curious: why are you avoiding using the attributes to generate the schemas?

If you prefer, please feel free to [join me on Slack](https://join.slack.com/t/manateeopensource/shared_invite/zt-4klcm69x-_MA8Z2ZSZ4JNu_d3lQOVPg) to discuss a bit more freely.

**Comment by gregsdennis** [comment]
Is anything else required for this? If not, I'm going to close it.  Thanks.

**Comment by karol-gro** [comment]
@gregsdennis Hi, we struggle with similar issue in our project.  We wanted to translate XML-docs into `description` field in JSON Schema. With custom refiner we managed to add them, but due to this caching mechanism, all properties of the same type get the same description.

We could use some attribute for that, but Visual Studio uses XML-docs for intellisense and we would need to place all descriptions twice

**Comment by gregsdennis** [comment]
From the [docs](https://gregsdennis.github.io/json-everything/usage/schema-generation.html):

> _**NOTE** Ideally, this functionality should be used to create a starting point in authoring a schema. The schemas output by this library should be reviewed by actual people prior to being put into a production system._

This is general advice that I and the rest of the JSON Schema specification team, including implementors of other libraries in other languages and frameworks, all agree on.  This does not pertain to just this library, but to ALL schema generation libraries.

I understand the desire to have a fully customizable, production-ready schema generated from your source.  However, this isn't possible right now, and I'm honestly not sure whether it's a realistic goal.

If you have a suggestion for a particular new feature, please open a new issue.

Regarding using XML docs, this library uses reflection.  XML docs are metadata stored in external files and are unavailable to the reflection APIs.

**Comment by genapi-bv** [comment]
> 
> 
> Is anything else required for this? If not, I'm going to close it. Thanks.

No, this is ok for me. Thanks again for your time and help!
